In [9]:
import sqlite3

conn = sqlite3.connect("library.db")
cur = conn.cursor()

In [10]:
cur.execute(""" 
CREATE TABLE books(
    book_id INTEGER PRIMARY KEY,
    title TEXT,
    author TEXT,
    year   INTEGER

)
""")

OperationalError: table books already exists

In [ ]:
#데이터 적재 - insert

In [11]:
book_list = [
    (1, "듄", "프랭크 허버트", 2021),
    (2, "은하수를 여행하는 히치하이커를 위한 안내서", "더글러스 애덤스", 1979),
    (3, "노르웨이의 숲", "무라카미 하루키", 1987),
    (4, "나미야 잡화점의 기적", "히가시노 게이고", 2012),
    (5, "더기버", "로이스 로리", 1993),
    
]

cur.executemany("INSERT INTO books VALUES (?, ?, ?, ?)", book_list)
conn.commit()    # 데이베이스에 변경사항 저장

IntegrityError: UNIQUE constraint failed: books.book_id

In [ ]:
import pandas as pd

df = pd.read_sql("select * FROM books", conn)
df

   book_id                    title    author  year
0        1                        듄   프랭크 허버트  2021
1        2  은하수를 여행하는 히치하이커를 위한 안내서  더글러스 애덤스  1979
2        3                  노르웨이의 숲  무라카미 하루키  1987
3        4              나미야 잡화점의 기적  히가시노 게이고  2012
4        5                      더기버    로이스 로리  1993

In [ ]:
data = pd.read_sql ("SELECT title, author FROM books", conn)
data

                     title    author
0                        듄   프랭크 허버트
1  은하수를 여행하는 히치하이커를 위한 안내서  더글러스 애덤스
2                  노르웨이의 숲  무라카미 하루키
3              나미야 잡화점의 기적  히가시노 게이고
4                      더기버    로이스 로리

In [ ]:
df  = pd.read_sql(

    "select * from books where year -> ?", conn, # 
    params=(1990,)
)

In [ ]:
df

   book_id                    title    author  year
0        1                        듄   프랭크 허버트  2021
1        2  은하수를 여행하는 히치하이커를 위한 안내서  더글러스 애덤스  1979
2        3                  노르웨이의 숲  무라카미 하루키  1987
3        4              나미야 잡화점의 기적  히가시노 게이고  2012
4        5                      더기버    로이스 로리  1993

### 조회
- where : 조건으로 행찾기
- order by : 정렬 오름차순 내림차순
- 집계함수 : 개수 합계 평균
- group by : 그룹별로 나눠서 집계

In [ ]:

more_books = [
      (6, "해리 포터와 마법사의 돌", "J.K. 롤링", 1997),
      (7, "반지의 제왕", "J.R.R. 톨킨", 1954),
      (8, "어린 왕자", "앙투안 드 생텍쥐페리", 1943),
      (9, "1984", "조지 오웰", 1949),
      (10, "동물 농장", "조지 오웰", 1945),
      (11, "위대한 개츠비", "F. 스콧 피츠제럴드", 1925),
      (12, "오만과 편견", "제인 오스틴", 1813),
      (13, "죄와 벌", "표도르 도스토옙스키", 1866),
      (14, "데미안", "헤르만 헤세", 1919),
      (15, "아몬드", "손원평", 2017),
      (16, "82년생 김지영", "조남주", 2016),
      (17, "완득이", "김려령", 2008),
      (18, "불편한 편의점", "김호연", 2021),
      (19, "달러구트 꿈 백화점", "이미예", 2020),
      (20, "지구 끝의 온실", "김초엽", 2021),
      (21, "모모", "미하엘 엔데", 1973),
      (22, "연금술사", "파울로 코엘료", 1988),
      (23, "사피엔스", "유발 하라리", 2011),
      (24, "침묵의 봄", "레이첼 카슨", 1962),
      (25, "총, 균, 쇠", "재레드 다이아몬드", 1997)
  ]

cur.executemany("INSERT INTO books VALUES (?, ?, ?, ?)", more_books)
conn.commit()

where 조건에 맞게

In [ ]:
data = pd.read_sql("select * from books where year > 2000", conn)
data

   book_id        title    author  year
0        1            듄   프랭크 허버트  2021
1        4  나미야 잡화점의 기적  히가시노 게이고  2012
2       15          아몬드       손원평  2017
3       16     82년생 김지영       조남주  2016
4       17          완득이       김려령  2008
5       18      불편한 편의점       김호연  2021
6       19   달러구트 꿈 백화점       이미예  2020
7       20     지구 끝의 온실       김초엽  2021
8       23         사피엔스    유발 하라리  2011

In [ ]:
#조건이 여러개
#and, or

In [ ]:
data = pd.read_sql("select * from books where author = '조지 오웰' and year > 1900", conn)

data

   book_id  title author  year
0        9   1984  조지 오웰  1949
1       10  동물 농장  조지 오웰  1945

In [ ]:
data = pd.read_sql("select * from books where title like '%왕자%'",conn)
data

   book_id  title       author  year
0        8  어린 왕자  앙투안 드 생텍쥐페리  1943

In [ ]:
data = pd.read_sql("select * from books where year in(2020,2021)",conn)
data

   book_id       title   author  year
0        1           듄  프랭크 허버트  2021
1       18     불편한 편의점      김호연  2021
2       19  달러구트 꿈 백화점      이미예  2020
3       20    지구 끝의 온실      김초엽  2021

In [ ]:
data = pd.read_sql("select * from books order by year DESC LIMIT 5",conn)

data

   book_id       title   author  year
0        1           듄  프랭크 허버트  2021
1       18     불편한 편의점      김호연  2021
2       20    지구 끝의 온실      김초엽  2021
3       19  달러구트 꿈 백화점      이미예  2020
4       15         아몬드      손원평  2017

In [ ]:
data = pd.read_sql("select * from books order by year ASC LIMIT 5",conn) # ASCENDING

data

   book_id    title       author  year
0       12   오만과 편견       제인 오스틴  1813
1       13     죄와 벌   표도르 도스토옙스키  1866
2       14      데미안       헤르만 헤세  1919
3       11  위대한 개츠비  F. 스콧 피츠제럴드  1925
4        8    어린 왕자  앙투안 드 생텍쥐페리  1943

In [ ]:
# 집계함수를 위한 테이블을 새로 하나 만들어봅시다.
# 집계 연습에 적합한 열을 포함해 테이블 생성
cur.execute("""
CREATE TABLE books_test (
    book_id INTEGER PRIMARY KEY,
    title   TEXT,
    author  TEXT,
    year    INTEGER,
    genre   TEXT,
    pages   INTEGER,
    price   INTEGER,
    rating  REAL
)
""")

book_list = [
    (1, "듄", "프랭크 허버트", 2021, "SF", 688, 18000, 4.8),
    (2, "은하수를 여행하는 히치하이커를 위한 안내서", "더글러스 애덤스", 1979, "SF", 320, 14000, 4.5),
    (3, "노르웨이의 숲", "무라카미 하루키", 1987, "소설", 572, 16000, 4.3),
    (4, "나미야 잡화점의 기적", "히가시노 게이고", 2012, "소설", 456, 15000, 4.6),
    (5, "더기버", "로이스 로리", 1993, "청소년", 280, 12000, 4.2),
    (6, "해리 포터와 마법사의 돌", "J.K. 롤링", 1997, "판타지", 320, 15000, 4.9),
    (7, "반지의 제왕", "J.R.R. 톨킨", 1954, "판타지", 980, 25000, 4.8),
    (8, "어린 왕자", "앙투안 드 생텍쥐페리", 1943, "동화", 120, 9000, 4.7),
    (9, "1984", "조지 오웰", 1949, "소설", 360, 13000, 4.6),
    (10, "동물 농장", "조지 오웰", 1945, "소설", 180, 10000, 4.4),
    (11, "위대한 개츠비", "F. 스콧 피츠제럴드", 1925, "소설", 240, 11000, 4.1),
    (12, "오만과 편견", "제인 오스틴", 1813, "소설", 480, 14000, 4.5),
    (13, "죄와 벌", "도스토옙스키", 1866, "소설", 720, 19000, 4.4),
    (14, "데미안", "헤르만 헤세", 1919, "소설", 220, 11000, 4.3),
    (15, "아몬드", "손원평", 2017, "청소년", 260, 13000, 4.6),
    (16, "82년생 김지영", "조남주", 2016, "소설", 190, 12000, 4.2),
    (17, "완득이", "김려령", 2008, "청소년", 240, 12000, 4.4),
    (18, "불편한 편의점", "김호연", 2021, "소설", 270, 14000, 4.5),
    (19, "달러구트 꿈 백화점", "이미예", 2020, "판타지", 300, 14000, 4.6),
    (20, "지구 끝의 온실", "김초엽", 2021, "SF", 390, 16000, 4.7),
    (21, "모모", "미하엘 엔데", 1973, "판타지", 350, 13000, 4.8),
    (22, "연금술사", "파울로 코엘료", 1988, "소설", 280, 12000, 4.3),
    (23, "사피엔스", "유발 하라리", 2011, "역사", 640, 22000, 4.7),
    (24, "침묵의 봄", "레이첼 카슨", 1962, "과학", 400, 18000, 4.5),
    (25, "총, 균, 쇠", "재레드 다이아몬드", 1997, "역사", 720, 24000, 4.6)
]

cur.executemany("""
INSERT INTO books_test
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
""", book_list)

conn.commit()

- count
- sum
- avg
- max,min

In [ ]:
data = pd.read_sql( """ 

select genre AS 장르,
    count(*) AS 책수,
    avg(price) as 평균가격

from books_test
group by genre
order by 책수
""", conn
) 
data

    장르  책수          평균가격
0   과학   1  18000.000000
1   동화   1   9000.000000
2   역사   2  23000.000000
3   SF   3  16000.000000
4  청소년   3  12333.333333
5  판타지   4  16750.000000
6   소설  11  13363.636364