# 판다스 데이터프레임 구조 메서드 연습

아래 `orders` 데이터프레임으로 행·열 구조, 자료형, 결측치, 기초 통계를 확인해 보세요.

In [19]:
import pandas as pd

data = {
    '주문번호': ['O-1001', 'O-1002', 'O-1003', 'O-1004', 'O-1005', 'O-1006',
             'O-1007', 'O-1008', 'O-1009', 'O-1010', 'O-1011', 'O-1012'],
    '주문일': ['2026-08-01', '2026-08-01', '2026-08-02', '2026-08-02', '2026-08-03', '2026-08-03',
             '2026-08-04', '2026-08-04', '2026-08-05', '2026-08-05', '2026-08-06', '2026-08-06'],
    '고객등급': ['신규', '일반', 'VIP', '일반', '신규', None, 'VIP', '일반', '신규', 'VIP', '일반', '신규'],
    '상품명': ['파이썬 입문', '데이터 분석 노트', '판다스 실습', '파이썬 입문', 'SQL 기초', '판다스 실습',
            '머신러닝 개론', 'SQL 기초', '데이터 분석 노트', '판다스 실습', '파이썬 입문', 'SQL 기초'],
    '카테고리': ['도서', '문구', '도서', '도서', '도서', '도서', '도서', '도서', '문구', '도서', '도서', '도서'],
    '수량': [1, 3, 2, 1, 2, 1, 1, 4, 2, 3, 1, 2],
    '단가': [18000, 4500, 22000, 18000, 15000, 22000, 30000, 15000, 4500, 22000, 18000, 15000],
    '할인율': [0.00, 0.10, 0.15, None, 0.00, 0.20, 0.10, 0.00, None, 0.15, 0.05, 0.00],
    '배송완료': [True, True, True, False, True, True, False, True, True, False, True, True],
    '리뷰점수': [5.0, 4.0, None, 5.0, 3.0, 4.0, None, 5.0, 4.0, 3.0, 5.0, None]
}

orders = pd.DataFrame(data)
orders['주문일'] = pd.to_datetime(orders['주문일'])
orders

      주문번호        주문일 고객등급        상품명 카테고리  수량     단가   할인율   배송완료  리뷰점수
0   O-1001 2026-08-01   신규     파이썬 입문   도서   1  18000  0.00   True   5.0
1   O-1002 2026-08-01   일반  데이터 분석 노트   문구   3   4500  0.10   True   4.0
2   O-1003 2026-08-02  VIP     판다스 실습   도서   2  22000  0.15   True   NaN
3   O-1004 2026-08-02   일반     파이썬 입문   도서   1  18000   NaN  False   5.0
4   O-1005 2026-08-03   신규     SQL 기초   도서   2  15000  0.00   True   3.0
5   O-1006 2026-08-03  NaN     판다스 실습   도서   1  22000  0.20   True   4.0
6   O-1007 2026-08-04  VIP    머신러닝 개론   도서   1  30000  0.10  False   NaN
7   O-1008 2026-08-04   일반     SQL 기초   도서   4  15000  0.00   True   5.0
8   O-1009 2026-08-05   신규  데이터 분석 노트   문구   2   4500   NaN   True   4.0
9   O-1010 2026-08-05  VIP     판다스 실습   도서   3  22000  0.15  False   3.0
10  O-1011 2026-08-06   일반     파이썬 입문   도서   1  18000  0.05   True   5.0
11  O-1012 2026-08-06   신규     SQL 기초   도서   2  15000  0.00   True   NaN

## 구조 확인 연습

아래 문제는 직접 코드를 작성해 보세요. 필요하면 한 문제씩 질문해도 됩니다.

1. 처음 5행과 마지막 3행을 각각 확인하세요.
2. 데이터프레임의 행 수와 열 수를 확인하세요.
3. 열 이름과 인덱스를 확인하세요.
4. 각 열의 자료형과 결측치 개수를 확인하세요.
5. 수치형 열의 기초 통계를 확인하세요.
6. 고객등급과 할인율의 결측치가 각각 몇 개인지 확인하세요.
7. 각 열의 고유값 개수를 확인하고, 가장 종류가 많은 열을 찾아보세요.
8. 주문번호에 중복값이 있는지 확인하세요.
9. 데이터프레임이 사용하는 메모리 크기를 확인하세요.

In [ ]:
# 여기에 1번 문제 코드를 작성하세요
orders.head(5)

     주문번호        주문일 고객등급     상품명 카테고리  수량     단가   할인율   배송완료  리뷰점수
2  O-1003 2026-08-02  VIP  판다스 실습   도서   2  22000  0.15   True   NaN
3  O-1004 2026-08-02   일반  파이썬 입문   도서   1  18000   NaN  False   5.0
4  O-1005 2026-08-03   신규  SQL 기초   도서   2  15000  0.00   True   3.0

In [26]:
# 여기에 2~4번 문제 코드를 작성하세요
display(orders.tail(3))
display(orders.shape)
display(orders.info())

      주문번호        주문일 고객등급     상품명 카테고리  수량     단가   할인율   배송완료  리뷰점수
9   O-1010 2026-08-05  VIP  판다스 실습   도서   3  22000  0.15  False   3.0
10  O-1011 2026-08-06   일반  파이썬 입문   도서   1  18000  0.05   True   5.0
11  O-1012 2026-08-06   신규  SQL 기초   도서   2  15000  0.00   True   NaN

(12, 10)

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   주문번호    12 non-null     str
 1   주문일     12 non-null     datetime64[us]
 2   고객등급    11 non-null     str
 3   상품명     12 non-null     str
 4   카테고리    12 non-null     str
 5   수량      12 non-null     int64
 6   단가      12 non-null     int64
 7   할인율     10 non-null     float64
 8   배송완료    12 non-null     bool
 9   리뷰점수    9 non-null      float64
dtypes: bool(1), datetime64[us](1), float64(2), int64(2), str(4)
memory usage: 1008.0 bytes

None

In [ ]:
# 여기에 5~9번 문제 코드를 작성하세요