### 데이터 프레임 : 표 -> 데이터 다루는 형태
- 엑셀과 같이 행(세로) 열(가로) 기본 형태
- 코드 몇 줄로 처리 가능
- 데이터 분석에 필수

### 1. Series - 한 줄 데이터
- 리스트와 비슷, 각 값마다 인덱스가 붙는다
- 표의 한 열을 나타냄

In [2]:
# 실슬
import pandas as pd

data = [81, 72, 33, 94]

df = pd.DataFrame(data)
data

[81, 72, 33, 94]

In [3]:
data_ser = pd.Series(data)
data_ser

0    81
1    72
2    33
3    94
dtype: int64

In [4]:
en_data = [92, 88, 67, 54]
en_data = pd.Series(en_data)

en_data

0    92
1    88
2    67
3    54
dtype: int64

#### 2. 데이터 프래임 만들기

- 데이터 프래임은 여러 시리즈를 병합
- 파이썬 딕셔너리 사용하는 것이 편함

In [6]:
data = {
    "이름": ["이현근", "김수연", "송수림"],
    "성별": ["남","여","여"],
    "나이" : [27,27,44],
    "취미" : ["코딩", "숨쉬기", "맛집탐방"],
    "키" : [183, 184, 182],
    "몸무게" : [62,None,None]
}

data

{'이름': ['이현근', '김수연', '송수림'],
 '성별': ['남', '여', '여'],
 '나이': [27, 27, 44],
 '취미': ['코딩', '숨쉬기', '맛집탐방'],
 '키': [183, 184, 182],
 '몸무게': [62, None, None]}

In [7]:
df = pd. DataFrame(data)
df

    이름 성별  나이    취미    키   몸무게
0  이현근  남  27    코딩  183  62.0
1  김수연  여  27   숨쉬기  184   NaN
2  송수림  여  44  맛집탐방  182   NaN

In [8]:

data = {
      "이름": ["이현근", "김수연", "송수림", "장안나", "백성현", "김병주", "유종혁", "주승우"],
      "성별": ["남", "여", "여", "여", "남", "남", "남", "남"],
      "나이": [27, 27, 44, 31, 29, 35, 26, 40],
      "취미": ["코딩", "숨쉬기", "맛집탐방", "독서", "축구", "영화감상", "게임", "등산"],
      "키": [182, 161, 165, 158, 175, 170, 178, 183],
      "몸무게": [62, None, None, 50, 68, 72, 75, 80]
  }
df = pd.DataFrame(data)
df

    이름 성별  나이    취미    키   몸무게
0  이현근  남  27    코딩  182  62.0
1  김수연  여  27   숨쉬기  161   NaN
2  송수림  여  44  맛집탐방  165   NaN
3  장안나  여  31    독서  158  50.0
4  백성현  남  29    축구  175  68.0
5  김병주  남  35  영화감상  170  72.0
6  유종혁  남  26    게임  178  75.0
7  주승우  남  40    등산  183  80.0

### 3. 데이터 형태 확인

- 데이터 앞 뒤를 확인 후 정상 파일인지 파악

In [11]:
df.tail(4)

    이름 성별  나이    취미    키   몸무게
4  백성현  남  29    축구  175  68.0
5  김병주  남  35  영화감상  170  72.0
6  유종혁  남  26    게임  178  75.0
7  주승우  남  40    등산  183  80.0

In [12]:
df.head(4)

    이름 성별  나이    취미    키   몸무게
0  이현근  남  27    코딩  182  62.0
1  김수연  여  27   숨쉬기  161   NaN
2  송수림  여  44  맛집탐방  165   NaN
3  장안나  여  31    독서  158  50.0

### 4. 표의 크기 - shagpe
- shape : 행과 열의 크기
- 괄호업이 사용 -> 메서드가 아닌 속성

In [13]:
df.shape

(8, 6)

##### 5. 전체 요약정보 - info()
- 채워진 값 개수 파악

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   성별      8 non-null      str
 2   나이      8 non-null      int64
 3   취미      8 non-null      str
 4   키       8 non-null      int64
 5   몸무게     6 non-null      float64
dtypes: float64(1), int64(2), str(3)
memory usage: 516.0 bytes

#### 6. 숫자 통계 요액 -descirbe()
- 숫자로 된 열의 평균 , 최대, 최소 기본 통계값
- 문자열 이 있은 열은 제외

In [15]:
df.describe()

              나이           키        몸무게
count   8.000000    8.000000   6.000000
mean   32.375000  171.500000  67.833333
std     6.674846    9.516902  10.666146
min    26.000000  158.000000  50.000000
25%    27.000000  164.000000  63.500000
50%    30.000000  172.500000  70.000000
75%    36.250000  179.000000  74.250000
max    44.000000  183.000000  80.000000

#### 7. 타입 형태 - 각 열이 어떤 자료형인지 파악 - dtypes
- int64, float64, object(글자형)

In [16]:
df.dtypes

이름         str
성별         str
나이       int64
취미         str
키        int64
몸무게    float64
dtype: object

#### 8. 열이름 목록 - columns

In [17]:
df.columns

Index(['이름', '성별', '나이', '취미', '키', '몸무게'], dtype='str')