### 조회와 선택

- 원하는 열과 행을 꺼내는 방법
- 조건식 사용
- 특정 열과 행을 선택하여 처리해야 함

In [33]:
import pandas as pd

In [34]:
df = pd.read_csv("../data/3-1_students.csv")
df.describe

<bound method NDFrame.describe of     이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석>

### 1. 열 하나 선택

In [35]:
df ['이름']

0    김민준
1    이서연
2    박도윤
3    최지우
4    정하준
Name: 이름, dtype: str

### 2. 열 선택
- df[['이름','국어','영어','수학']]

In [36]:
df[['이름','국어','영어','수학']]

    이름    국어    영어   수학
0  김민준  90.0  80.0  100
1  이서연  85.0  92.0   78
2  박도윤   NaN  75.0   88
3  최지우  70.0   NaN   65
4  정하준  88.0  95.0   결석

#### 3. 행 선택 - loc 사용

- loc 행의 인덱스 라벨명 행 꺼내기
- 지금 위의 데이터는 라벨명 1,2,3,4

In [37]:
df.loc[0]
df.loc[0:2]

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88

In [40]:
#df.index = ['A','B','C','D','E','F'] # 인덱스 넘버가 아닌 라벨을 사용
df.loc["A":"D"][["반"]]

Empty DataFrame
Columns: [반]
Index: []

### 4. 행 선택 iloc 
- 몇 번째인지 순서를 꺼낸다

In [82]:
df.iloc[3:5,2:4]

  성별    국어
3  여  70.0
4  남  88.0

In [28]:
df.iloc[0:4]

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65

In [80]:
df.loc[0:3][["반","성별","국어","영어"]]
df.loc[0]

이름     김민준
반        A
성별       남
국어    90.0
영어    80.0
수학     100
Name: 0, dtype: object

In [ ]:
df[df['성별']=="남"]
df[df['국어']>=80]
# df[df['수학']>=80] # 결적으로 전처리 필요

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
4  정하준  A  남  88.0  95.0   결석

#### 5. 여러 조건 - &그리고, | 또는

- 조건이 여러개면 and , or를 사용
-

In [ ]:
df[(df['반']=="A") & (df['국어'] >= 85)]
# 연습

Empty DataFrame
Columns: [이름, 반, 성별, 국어, 영어, 수학]
Index: []

In [74]:
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석

In [72]:
# 성별이 여자이면서 수학 점수가 70점 이상인 학생
df[(df['성별']=="여") & (df['영어'] >= 90)]

    이름  반 성별    국어    영어  수학
1  이서연  B  여  85.0  92.0  78

In [ ]:
# 성별이 여자이면서 국어 점수가 80점 이상인 학생
df[(df['성별']=="여") & (df['국어']>=80)]

    이름  반 성별    국어    영어  수학
1  이서연  B  여  85.0  92.0  78

In [81]:
df[(df['국어']>=86) | (df['영어']>=90)]

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
4  정하준  A  남  88.0  95.0   결석