##### 데이터 정제 및 전처리
- 중요한 이유
    - 데이터는 여러 잘못된 데이터가 항상 존재
    - 그대로 분석할 수 없는 상태
    - 정제하는 게 필수

In [3]:
import pandas as pd

In [39]:
df = pd.read_csv("../data/3-1_students.csv")
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

### 1. 결측치 -데이터가 없는 경우
- isna().sum() 일별 결측치 개수 파악
- isna() 각 칸이 비어있는 지 여부
- sum() 전체 합 : true --> 1 , else --> 0

In [ ]:
df.isna() # df.isnull()
df.style.highlight_null(color="gray")
df.isna().sum()
df.isnull()

      이름      반     성별     국어     영어     수학
0  False  False  False  False  False  False
1  False  False  False  False  False  False
2  False  False  False   True  False  False
3  False  False  False  False   True  False
4  False  False  False  False  False  False
5  False  False  False  False  False  False

##### 결측치 제거
- dropna() : 결측치가 있는 행 또는 열을 제거하는 메서드
- 표준 표현 Not Available -> NA을 사용

In [7]:
df.dropna()

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
4  정하준  A  남  88.0  95.0   결석

In [8]:
df 
df_copy = df.copy()

In [ ]:
df =df.dropna() #결측지 없는 상태
df_copy = df.copy() # 결측지 없앤 후 데이터 프레임을 df_copy 담기

In [19]:
df = pd.read_csv("../data/3-1_students.csv")
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

In [ ]:
# 결측리를 평균으로 채우기

korean_score = df['국어'].mean() #평균
korean_score

np.float64(83.6)

In [21]:
df['영어'] = df['영어'].fillna(df['영어'].mean())
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0  86.8   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

In [22]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

### 5. 중복제거
- df.drop_duplicates() - 원본에 영향을 주지는 않음

In [23]:

df = df.drop_duplicates()
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0  86.8   65
4  정하준  A  남  88.0  95.0   결석

### 6. 타입 수정
- 숫자가 아닌 부분은 -> None
- pd.to_numeric()

In [26]:
df['수학']=pd.to_numeric(df['수학'], errors="coerce") # 숫자가 아닌 부분은 -> None
df

    이름  반 성별    국어    영어     수학
0  김민준  A  남  90.0  80.0  100.0
1  이서연  B  여  85.0  92.0   78.0
2  박도윤  A  남   NaN  75.0   88.0
3  최지우  B  여  70.0  86.8   65.0
4  정하준  A  남  88.0  95.0    NaN

In [28]:
df['수학']=df['수학'].fillna(df['수학'].mean())
df # 숫자가 아닌 부분은 -> None

    이름  반 성별    국어    영어      수학
0  김민준  A  남  90.0  80.0  100.00
1  이서연  B  여  85.0  92.0   78.00
2  박도윤  A  남   NaN  75.0   88.00
3  최지우  B  여  70.0  86.8   65.00
4  정하준  A  남  88.0  95.0   82.75

### 7.이상치 확인

- 만약 사실 위에서 수학은 90점이 만점 --> 10점은 수행이어서 90점 이상은 오류가 있음

In [31]:
print(len(df[df['수학'] > 90]))

1