# 1. 대회 데이터 구조 확인

원본 `data/open.zip`을 수정하거나 압축 해제하지 않고 파일 구성과 dev 데이터 구조를 확인한다.

In [2]:
from pathlib import Path
import gzip, io, json, zipfile
import pandas as pd

ZIP_PATH = Path('../data/open.zip')
assert ZIP_PATH.exists(), ZIP_PATH
print(ZIP_PATH, ZIP_PATH.stat().st_size)

..\data\open.zip 216827912

### 2. 데이터 크기 및 데이터 파일명 확인

In [3]:
with zipfile.ZipFile(ZIP_PATH) as z:
    infos = z.infolist()
    for info in infos:
        print(f'{info.filename}\t{info.file_size:,} bytes')
print('파일 수:', len(infos))

README.md	7,176 bytes
baseline/requirements.txt	273 bytes
baseline/script.py	24,507 bytes
data/test.jsonl.gz	133,965 bytes
data/법령패키지/법령/(계약예규) 공동계약운용요령.txt	44,425 bytes
data/법령패키지/법령/(계약예규) 정부 입찰·계약 집행기준.txt	357,167 bytes
data/법령패키지/법령/국가를 당사자로 하는 계약에 관한 법률 등의 재정경제부장관이 정하는 고시금액.txt	4,095 bytes
data/법령패키지/법령/국가를 당사자로 하는 계약에 관한 법률 시행규칙.txt	253,770 bytes
data/법령패키지/법령/국가를 당사자로 하는 계약에 관한 법률 시행령.txt	331,790 bytes
data/법령패키지/법령/국가를 당사자로 하는 계약에 관한 법률.txt	51,478 bytes
data/법령패키지/법령/소상공인기본법 시행령.txt	31,101 bytes
data/법령패키지/법령/소상공인기본법.txt	29,231 bytes
data/법령패키지/법령/소프트웨어 진흥법 시행령.txt	100,223 bytes
data/법령패키지/법령/소프트웨어 진흥법.txt	88,410 bytes
data/법령패키지/법령/중소 소프트웨어사업자의 사업 참여 지원에 관한 지침.txt	244,210 bytes
data/법령패키지/법령/중소기업기본법 시행령.txt	91,044 bytes
data/법령패키지/법령/중소기업기본법.txt	45,740 bytes
data/법령패키지/법령/중소기업자간 경쟁제품 및 공사용자재 직접구매 대상 품목 지정 내역.txt	3,995 bytes
data/법령패키지/법령/중소기업자간 경쟁제품 직접생산 확인기준.txt	175,177 bytes
data/법령패키지/법령/중소기업제품 구매촉진 및 판로지원에 관한 법률 시행규칙.txt	125,248 bytes
data/법령패키지/법령/중소기업제품 구매촉진 및 판로지원에 관한 법률 시행령.txt	113,231 bytes
data/법령패키지/법령/중소기업제품 구매촉진 및 판로지원에 관한 법률.txt	101,444 bytes
data/법령패키지/법령/지방자치단체 입찰 및 계약 집행기준.txt	803,014 bytes
data/법령패키지/법령/지방자치단체 입찰시 낙찰자 결정기준.txt	921,863 bytes
data/법령패키지/법령/지방자치단체를 당사자로 하는 계약에 관한 법률 시행규칙.txt	221,615 bytes
data/법령패키지/법령/지방자치단체를 당사자로 하는 계약에 관한 법률 시행령.txt	342,537 bytes
data/법령패키지/법령/지방자치단체를 당사자로 하는 계약에 관한 법률.txt	76,831 bytes
data/법령패키지/중기부고시/중기부고시_경쟁제품_세부품명.csv	75,014 bytes
data/법령패키지/중기부고시/중기부고시_경쟁제품_제2025-96호.hwpx	158,694 bytes
data/정답스키마_디코딩.json	13,751 bytes
data/항목표.json	11,273 bytes
dev.jsonl.gz	2,270,965 bytes
dev_labels.csv	28,044 bytes
sample_submission.csv	1,018 bytes
train_unlabeled.jsonl.gz	213,346,480 bytes
파일 수: 35

  ### 3. `dev.jsonl.gz` 데이터 읽기 및 구조 확인

  ### 확인 항목:
  - 전체 데이터 건수
  - 각 데이터의 주요 키
  - 첫 번째 데이터의 `id`
  - 데이터별 포함 문서 수
  - `meta` 메타데이터 구조

  - `id`: 데이터 식별자
  - `docs`: 참고 문서 목록
  - `meta`: 데이터 메타정보
  - `anon_applied`: 익명화 적용 여부
  - `assembly_policy_version`: 정책 버전
  - `dropped_doc_counts`: 제외된 문서 수
  - `input_completeness`: 입력 데이터 완전성

In [4]:
def load_jsonl_from_zip(zip_path, member, limit=None):
    rows = []
    with zipfile.ZipFile(zip_path) as z, z.open(member) as raw:
        with gzip.GzipFile(fileobj=raw) as stream:
            for line in stream:
                if line.strip():
                    rows.append(json.loads(line.decode('utf-8')))
                    if limit and len(rows) >= limit:
                        break
    return rows

dev = load_jsonl_from_zip(ZIP_PATH, 'dev.jsonl.gz')
print('dev rows:', len(dev))
print('top keys:', sorted(dev[0]))
print('first id:', dev[0]['id'])
print('docs:', len(dev[0]['docs']), 'meta keys:', len(dev[0]['meta']))

dev rows: 200
top keys: ['anon_applied', 'assembly_policy_version', 'docs', 'dropped_doc_counts', 'id', 'input_completeness', 'meta']
first id: PPS-DEV-01
docs: 2 meta keys: 21

### 4. dev 데이터 식별자, 문서 수, 문서 유형 확인
- id가 비어 있는 데이터가 있는지
- 중복된 id가 있는지
- 데이터마다 문서가 몇 개씩 포함되어 있는지
- 문서 유형에는 어떤 값이 있는지
- 데이터 누락 또는 중복 파악

In [5]:
ids = [r['id'] for r in dev]
print('id 결측:', sum(not x for x in ids))
print('id 중복:', len(ids) - len(set(ids)))
print('docs 개수 분포:', pd.Series([len(r['docs']) for r in dev]).value_counts().sort_index())
print('문서 유형:', sorted({d['type'] for r in dev for d in r['docs']}))

id 결측: 0
id 중복: 0
docs 개수 분포: 1    67
2    92
3    41
Name: count, dtype: int64
문서 유형: ['공고문', '과업지시서', '규격서', '제안요청서']

### 5. dev_labels.csv의 정답 라벨 확인

- 라벨 데이터의 행과 열 개수
- 라벨 컬럼 이름
- v1~v24 라벨 값의 종류
- id 중복 여부
- dev 라벨 파일을 연결가능한 지 , 라벨 형식 정상 여부 확인

  - 총 200건의 라벨 데이터로 구성되어 있다.
  - 전체 컬럼은 49개이다.
    - `id`: 데이터 식별자
    - `v1~v24`: 24개의 이진 라벨
    - `e1~e24`: 24개의 추가 라벨
  - `v` 계열 라벨은 `0`과 `1`로 구성되어 있
  다.
  - `id` 중복은 발견되지 않았다.

In [7]:
with zipfile.ZipFile(ZIP_PATH) as z:
    labels = pd.read_csv(io.BytesIO(z.read('dev_labels.csv')))
print(labels.shape)
print(labels.columns.tolist())
print('v 값:', sorted(set(labels.filter(regex=r'^v\d+$').to_numpy().ravel())))
print('label id 중복:', labels['id'].duplicated().sum())

(200, 49)
['id', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10', 'v11', 'v12', 'v13', 'v14', 'v15', 'v16', 'v17', 'v18', 'v19', 'v20', 'v21', 'v22', 'v23', 'v24', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6', 'e7', 'e8', 'e9', 'e10', 'e11', 'e12', 'e13', 'e14', 'e15', 'e16', 'e17', 'e18', 'e19', 'e20', 'e21', 'e22', 'e23', 'e24']
v 값: [np.int64(0), np.int64(1)]
label id 중복: 0

## 6. 확인 결과 기록

- 원본 ZIP은 읽기 전용으로 사용한다.
- `dev.jsonl.gz`와 `dev_labels.csv`는 `id`로 대응한다.
- 다음 단계는 `--mock` 실행과 제출 CSV 검증이다.

In [28]:
def show_case(target_id):
    record = next(r for r in dev if r["id"] == target_id)
    answer = labels[labels["id"] == target_id].iloc[0]

    print("공고 ID:", target_id)
    print("문서:", [(d["type"], len(d["text"])) for d in
    record["docs"]])

    print("위반 항목:")
    for i in range(1, 25):
        if answer[f"v{i}"] == 1:
            print(f"v{i}:", answer[f"e{i}"])

In [35]:
for target_id in [r["id"] for r in dev[8:10]]:
      show_case(target_id)
      print("\n" + "-" * 60)

공고 ID: PPS-DEV-09
문서: [('공고문', 8770), ('규격서', 2493)]
위반 항목:
v7: 마. 주된 영업소(본사 소재지를 말함)가 입찰공고일 현재 광주광역시, 전라남도의 관할구역 안에 있어야 합니다.
v9: Chipset: GB10 Grace Blackwell Superchip

------------------------------------------------------------
공고 ID: PPS-DEV-10
문서: [('공고문', 10496), ('과업지시서', 7349)]
위반 항목:
v7: ③ 입찰공고일 전일부터 입찰일(낙찰자는 계약체결일)까지 법인등기부상 본점 소재지(개인사업자인 경우에는 사업자등록증 또는 관련 법령에 따른 허가·인가·면허·등록·신고 등에 관련된 서류에 기재된 사업장의 소재지)를 계속하여 전북특별자치도 또는 충청남도 또는 충청북도에 둔 업체여야 합니다.

------------------------------------------------------------

In [36]:
ids = [r["id"] for r in dev[:10]]

labels[labels["id"].isin(ids)].filter(regex=r"^v\d+$").sum()

v1     1
v2     2
v3     2
v4     1
v5     1
v6     1
v7     2
v8     1
v9     1
v10    0
v11    0
v12    0
v13    0
v14    0
v15    0
v16    0
v17    0
v18    0
v19    0
v20    0
v21    0
v22    0
v23    0
v24    0
dtype: int64

In [37]:
for i in range(1, 25):
    col = f"v{i}"
    found = labels[labels[col] == 1]

    if len(found) > 0:
        print(col, "대표 ID:", found.iloc[0]["id"])
    else:
        print(col, "위반 사례 없음")

v1 대표 ID: PPS-DEV-01
v2 대표 ID: PPS-DEV-02
v3 대표 ID: PPS-DEV-04
v4 대표 ID: PPS-DEV-06
v5 대표 ID: PPS-DEV-07
v6 대표 ID: PPS-DEV-08
v7 대표 ID: PPS-DEV-09
v8 대표 ID: PPS-DEV-05
v9 대표 ID: PPS-DEV-09
v10 대표 ID: PPS-DEV-13
v11 대표 ID: PPS-DEV-14
v12 대표 ID: PPS-DEV-15
v13 대표 ID: PPS-DEV-16
v14 대표 ID: PPS-DEV-17
v15 대표 ID: PPS-DEV-18
v16 대표 ID: PPS-DEV-20
v17 대표 ID: PPS-DEV-21
v18 대표 ID: PPS-DEV-22
v19 대표 ID: PPS-DEV-23
v20 대표 ID: PPS-DEV-24
v21 대표 ID: PPS-DEV-25
v22 대표 ID: PPS-DEV-26
v23 대표 ID: PPS-DEV-27
v24 대표 ID: PPS-DEV-29

### 7. 샘플 10개 파일 테스트

In [8]:
pilot = dev[:10]

pilot_ids = pd.DataFrame({
    "id": [r["id"] for r in pilot],
    "v1": "",
    "v2": "",
    "v3": "",
    "e1": "",
    "e2": "",
    "e3": "",
    "memo": "",
})

pilot_ids.to_csv(
    "C:/study-contests/outputs/labeling_pilot_10.csv",
    index=False,
    encoding="utf-8-sig",
)

pilot_ids

           id v1 v2 v3 e1 e2 e3 memo
0  PPS-DEV-01
1  PPS-DEV-02
2  PPS-DEV-03
3  PPS-DEV-04
4  PPS-DEV-05
5  PPS-DEV-06
6  PPS-DEV-07
7  PPS-DEV-08
8  PPS-DEV-09
9  PPS-DEV-10

In [39]:
r = dev[0]
print("공고 ID:", r["id"])

for d in r["docs"]:
    print("\n문서 유형:", d["type"]) 
    print(d["text"])

공고 ID: PPS-DEV-01

문서 유형: 공고문
ㆍ[수요기관(공기업)] 공고 [공고번호]

[긴급] 용 역 입 찰 공 고
( 총액입찰, 제한경쟁(지역, 중소기업), 협상에 의한 계약 )

1. 입찰개요

구분 주요 내용 비고
‣ 용 역 명 : 2026 별바다부산 나이트 마켓 운영 대행 용역
입찰에 부치는 사항 ‣ 용역기간 : 계약체결일로부터 ~ 2026. 11. 30. 1항
‣ 기초금액 : 금310,000,000원(부가가치세 포함)

입찰 및 계약방법 ‣ 전자입찰 및 계약, 총액, 제한경쟁, 협상에 의한 계약, 상생결제 2항

‣ 업종제한 : 기타자유업(행사대행업,업종코드 : 9901)
‣ 직접생산 : 기타 행사기획 및 대행 서비스(세부품명번호: 8014199001)
입찰참가자격 축제기획및대행서비스 (세부품명번호: 9015189001) 4항
‣ 지역제한 : 부산광역시에 주된 영업소를 둔 업체
‣ 기업형태 : 중소기업, 소상공인

공동계약 가능여부 ‣ 공동계약 가능(공동이행) 4항

하도급 가능여부 ‣ 하도급 가능 4항

가격입찰서 제출 ‣ 2026. 2. 11. (수) 09:00 ~ 2026. 2. 19. (목) 12:00 ※ 전자제출 6항

제안서 제출 ‣ 2026. 2. 19 (목) 13:00 ~ 16:00 ※ 방문제출 7항

※ 입찰의 세부내용은 필히 본문 내용을 확인하시기 바랍니다.

2. 본 입찰에 참가하고자 하는 자는 국가종합전자조달시스템의 본 공고문과 함께 붙임
과업지시서, 제안요청서, 국가종합전자조달시스템 전자입찰특별유의서, 지방자치단체
입찰 및 계약집행기준, 계약일반조건 및 특수조건, 입찰유의서 등 기타 입찰에 필요
한 모든 사항을 열람 및 완전히 숙지하고 입찰에 응하셔야 하며, 이를 숙지하지 못
하여 발생한 불이익은 입찰참가자에게 있습니다.
<입찰 문의사항 안내>
☞ 서류 제출, 제안서 평가 관련 : [부서] 사업담당자 ☎[전화번호]
☞ 입찰 계약 체결 관련 : 인재개발팀 입찰담당자 ☎[전화번호]

3. 본 입찰은 청렴계약(서약)제가 적용됩니다.
<공익신고 안내>
☞ 본 입찰과 관련 비리·불공정행위가 있는 경우 : [부서] ☎ [전화번호]
☞ 공익신고 문의 : 국민권익위원회 ☎국번없이 110
1. 입찰에 부치는 사항 (단위 : 원)

용역명 위치 사업량 용역기간 추정금액 추정가격 기초금액

2026 별바다부산 제안요청서 계약체결일로부터
부산소재 310,000,000 281,818,182 310,000,000
나이트마켓 운영 대행 용역 참조 2026.11.30.까지

2. 입찰 및 계약방식 : 전자입찰 및 계약, 총액입찰, 제한경쟁, 협상에 의한
계약(긴급), 상생결제

3. 낙찰자 결정방법 : 「지방계약법」시행령 제43조에 따른 협상에 의한 계약
4. 입찰참가자격

가. 『지방계약법』 시행령 제13조 및 같은 법 시행규칙 제14조에 의한 입찰
참가자격을 갖춘자로 「국가종합전자조달시스템 입찰참가자격 등록규정」에
따라 임찰 마감일 전일까지 조달청 나라장터(G2B)에 다음 업종으로 입찰
참가 등록을 필한 업체
- 업종: 기타자유업(행사대행업) [업종코드: 9901]
나. 『판로지원법』 제9조 및 같은 법 시행령 제10조에 따라 다음 세부품명으로
‘직접생산확인증명서’를 모두 소지한 자로서 전자입찰서 제출 마감일 전일까지
발급되어 유효기간 내 있어야 함
- 세부품명: 기타 행사기획 및 대행서비스(세부품명번호 8014199001),
축제기획 및 대행 서비스(세부품명번호 9015189001)
다. 입찰공고일 전일부터 입찰일(낙찰자는 계약체결일)까지 법인등기부등본
(개인사업자는 사업자등록증) 상 부산광역시에 주된 영업소를 둔 업체
라. 본 용역은 「고등교육법」 제2조에 따른 대학 또는 「산업교육진흥
및 산학연협력촉진에 관한 법률」 제25조에 따른 산학협력단만 참여 가능함
마. 중소기업기본법 제2조에 따른 중·소기업 또는 『소상공인 보호 및 지원에 관
한 법률』 제2조에 따른 소상공인으로서‘중·소기업, 소상공인 확인서’를
소지한 자
- 중소기업확인서를 전자입찰서 제출 마감일 전일까지 신청한 자는 입찰참가
가능하나 다음의 어느 하나에 해당하는 경우에는 참가자격 없음
① 입찰서 제출일로부터 5일 이내에 중소기업확인서가 발급되지 않은 경우
② 발급된 중소기업확인서가 입찰 참가자격의 기업 구분과 다른 경우
③ 발급된 중소기업확인서의 유효기간 시작일이 전자입찰서 제출 마감일 이후인 경우
④ 전자입찰서 제출 마감일 이후 중소기업확인서를 신청한 경우
- 중소기업확인서는 중소기업제품 공공구매 종합정보망(http://www.smpp.go.kr)
에서 확인하며, 확인이 되지 않을 경우 입찰참가 자격 없음
- 「판로지원법」제33조에 따라 중소기업 간주 특별법인의 경우 입찰 참가
가능하며 특별법인임을 확인할 수 있는 서류 제출 필수
바. 입찰참가 등록마감일 현재「지방계약법」시행령 제13조 및 같은 법 시행
규칙 제14조의 규정에 의한 경쟁입찰 참가자격을 갖추고 같은 법 제31조
및 시행령 제92조에 의한 부정당업자의 입찰참가자격 제한기간 중에 있지
아니한 자
사. 미자격자가 고의로 입찰에 참가하여「지방계약법」시행령 제92조 제2항에
해당된다고 판단될 경우 부정당업자로 제재할 수 있음
아. 낙찰자는 계약체결일까지 당해자격을 계속 유지하여야 함
- 공동수급에 관한 사항 : 공동이행 가능
가. 공동수급체 구성원 전체는 입찰 참가자격을 모두 갖추어야 함
나. 공동수급체 구성원은 대표사를 포함하여 3개사 이하로 하며, 최소 지분율은
5% 이상으로 한다
다. 하나의 업체가 두 개 이상의 공동수급체를 구성하여 중복 불가
라. 공동 수급체인 경우 대표[담당자] 투찰 가능
마. 공동수급협정서는 2026. 2. 18.(수) 18:00 까지국가종합전자조달시스템을 통하여
제출하여야 하며, 대표자를 포함한 구성원들이 각각의 분담내용을 국가종합
전자조달시스템에 제출한 후 반드시 대표자가 공동수급구성원 각각의
출자비율 또는 분담 내용을 승인하고 이를 제출한 것으로 본다
- 하도급에 관한 사항 : 하도급 가능
가. 하도급에 관한 사항은 과업내용서, 제안요청서에 따르며, 하도급에 관한
사항을 정하고 있지 않을 경우에는 계약 체결 후 계약자와 수요기관 간
협의에 의해 정해진 바에 따름
나. 하도급을 실시하려는 경우 과업내용서 또는 제안요청서, 관련 법령 등에서
정한 하도급 승인 절차 등의 관련 규정을 준수하여야 함
다. 수요기관의 승인 없이 하도급을 하거나 관련법령에 따른 하도급 규정을
위반하여 하도급을 한 경우에는 관계법령(「지방계약법」등)에 따라 계약 해지·
해제 또는 입찰 참가 자격 제한을 받을 수 있음
5. 입찰참가 신청 및 입찰보증금
가. 본 입찰은 조달청 입찰참가자격 등록증 상의 내용에 따라 입찰에 참가하는
전자 입찰입니다.
나. 공고문 4항 입찰참가자격 중 ‘가’의 내용에 따라 입찰참가자격 등록을
하였거나, 나라장터 시스템에 등록사항이 게재된 경우에 입찰참가신청을
한 것으로 봅니다.
다. 입찰보증금 납부 및 공사 귀속
- 입찰보증금은 전자입찰서상의 지급각서로 대체합니다.
- 입찰보증금의 귀속 등에 관하여는 「지방자치단체를 당사자로 하는 계약에
관한 법률 시행령 」 제 조 및 제 조에 의합니다
37 38 .

- 낙찰자가 낙찰자 선정 통보일로부터 10일 이내에 계약을 체결하지 않아 입찰
보증금 귀속 사유가 발생한 때에는 지급각서에 따라 입찰금액의 5%(원단위
절상)의 금액을 지체 없이 현금으로 납부하여야 합니다.

6. 입찰서 제출
가. 본 입찰은 전자입찰로만 집행하며, 전자입찰서는 반드시 국가종합전자조
시스템 나라장터 홈페이지(https://www.g2b.go.kr/)의 전자입찰시스템을 이
용하여 제출해야 합니다.
나. 투찰금액은 면세사업자라 하더라도 부가가치세를 포함한 금액으로 제출하
시기 바랍니다.
다. 본 입찰은 전자입찰 입찰자 신원확인제도가 적용됨에 따라 개인인증서를
보유한 대표자 또는 입찰 대리인만이 입찰서 제출이 가능합니다.
라. 전자입찰서 제출확인은 조달청 국가종합전자조달시스템의 보낸 문서함에서
확인하시기 바랍니다.
마. 가격입찰서 제출일자 : 2026. 2. 11. (수) 9:00 ~ 2. 19.(목) 12:00

바. 예정가격은 지방계약법 시행령 제8조 제2항에 의거 작성하지 않습니다. (비예가)

7. 제안서 제출
가. 제출일자 : 2026. 2. 19. (목) 13:00 ~ 16:00
나. 제출방식 : 방문 제출
다. 제 출 처 : [수요기관(공기업)] [부서] 사업담당자 ☎ [전화번호]

- [지역:r1|단위=기초|광역=부산광역시] [상세주소],([지역:r2|단위=읍면동|광역=부산광역시], [상세주소])
라. 제안서 및 제출 서류 일체는 PDF파일과 책자 형식으로 제출해야 하며,
전자파일은 200MB 초과할 수 없습니다.
마. 제출 서류 목록은 제안요청서 참조

8. 제안서 평가위원회
※ 일정, 장소는 향후 변동될 수 있음
가. 일시: 2026. 2. 24.(화) 16:00 ~ 18:00
나. 장소: [수요기관(공기업)] 본부 대회의실 ([지역:r1|단위=기초|광역=부산광역시] [상세주소], [상세주소])
다. 발표는 본 과업수행에 참여하는 인력이 진행하며, 발표자료는 PDF로 해야
하며, 기 제출한 파일을 사용은 발표당일 변경 불가함
라. 발표자는 재직증명서와 신분증을 반드시 지참해야 하고, 최대 2명 까지 입장 가능
마. 발표 내용과 제안서의 내용이 상이할 경우 감점 처리할 수 있고, 발표 내용
보다 제안서가 우선함
바. 발표순서는 제안서 제출 시 추첨한 알파벳 순으로 하고, 발표 시간은 제안사
별 30분 내외(발표 20분, 질의응답 10분)로 하며, 발표 시간 20분 초과시
분당 0.5점 감점

9. 협상대상자 선정 및 협상기준
가. 제안서 평가결과 기술능력과 가격 평가점수의 합산점수가 70점 이상인 자
를 협상적격자로 선정합니다.
나. 협상적격자의 기술능력평가 점수와 입찰가격평가 점수를 합산하여 합산점
수가 가장 높은 자를 우선협상대상자로 선정합니다.
- 합산점수가 동일한 제안자가 2인 이상일 경우, 기술능력평가 점수가 높은 자를
우선순위자로 하고, 기술능력평가 점수도 동일한 경우에는 추첨으로 정한다.
- 제안서 평가 요소 및 평가방법 : 기술능력평가 90%, 입찰가격평가 10%
다. 우선협상대상자부터 순차적으로 협상을 실시하여 낙찰자 결정합니다.
라. 기타 사항은 행정안전부 계약예규 “협상에 의한 계약 체결기준”에 의합니다.
10. 청렴계약 이행 의무 준수
가. 본 입찰에 참가하는 자는 청렴계약이행을 위한 [수요기관(공기업)] 청렴계약입
찰유의서 및 특수조건을 준수하겠다는 서약서를 제출한 것으로 간주하며
최종낙찰자로 선정될 경우 ‘청렴계약이행서약서’를 제출하여야 함
· ·
나. 본 입찰은 청렴 공정한 계약 진행을 위한 계약 입찰 자율 신고제가 적용되
는 입찰로 해당자는 다음과 같이 신고하여야 함
- 신고 대상: 배우자 및 4촌 이내의 친족이 공사에 재직하고 있는 우선협상대상자
- 신고 방법: 신고 서식 작성 후 계약부서로 송부
- 신고 시기: 적격심사 서류 제출 시
※ 신고자에게 입찰 및 계약에 대한 어떠한 불이익도 없음

11. 안전보건 확보 의무 준수
가. 입찰참가자는『중대재해처벌법』제4조, 제5조 및 같은 법 시행령 제4조제9
호에 의거 다음 안전보건 확보 의무사항을 준수하여야 함

① 재해예방에 필요한 인력·예산·점검 등 안전보건관리체계의 구축 및 그 이행에 관한 조치
② 재해 발생 시 재발방지 대책의 수립 및 그 이행에 관한 조치
③ 중앙행정기관·지방자치단체가 관계 법령에 따라 개선·시정 등을 명한 사항의 이행에 관한 조치
④ 안전·보건 관계 법령에 따른 의무이행에 필요한 관리상의 조치
나. 안전보건관리 준수 서약제 실시
- 본 입찰에 참가하고자 하는 자는 근로자의 중대재해 예방을 위해 위 ‘안전
보건 확보 의무사항‘을 숙지한 후 입찰에 응해야 하며, 입찰서를 제출자는
안전보건관리 준수 서약서를 제출한 것으로 간주함
- 추후, 낙찰자는 계약 체결 시 대표자가 서명한 ’안전보건관리 준수 서약서‘를
제출하여야 함

12. 지식재산권의 귀속 등
가. 제출된 서류 및 자료는 입찰의 종료 후 입찰자의 요구 시 반환하며, 입찰일
로부터 2주간 반환요청이 없는 경우 이를 폐기함
나. 입찰을 위해 제출된 서류 및 자료의 소유권 및 저작권 등은 공사에 귀속되
지 않으며, 다만, 공사는 필요시 제출된 서류 및 자료의 활용을 위해 입찰
자와 협의할 수 있음
다. 용역 결과물에 대한 저작권 등 지식재산권은 공사와 계약상대자가 공동으로
소유하며, 이에 대한 구체적인 사항은 과업내용서 내 계약 일반조건에 따름

13. 기타 유의사항
가. 『지방계약법』 시행령 제39조에 의거 입찰 참가자격이 없는 자가 참가한 입찰
이나 같은법 시행규칙 제42조에 따른 그 밖에 사유에 해당하는 입찰은 무효
나. 본 입찰에 참가한 자가 계약체결일 이전에 부도․파산․해산․영업정지 등의
상태에 있는 경우 계약 상대자에서 제외
다. 본 입찰의 낙찰자는 근로자와 고용계약을 체결할 경우 최저임금법 제10조
제1항의 규정에 의하여 고용노동부 장관이 고시한 최저임금액 미만으로 계
약할 수 없음
라. 입찰 참가에 따른 일체의 소요 비용은 입찰 참가자가 부담
마. 공고문에 언급되지 아니한 사항은 입찰공고일 현재 적용되는 계약 관계법
령, 계약예규, 고시 등 관계 규정에 의함
바. 입찰관련서류는 국가종합전자조달시스템 홈페이지(나라장터)의 본 공고상세
조회(입찰권유서)에서도 조회 및 열람 가능 함
사. 전자입찰 참가희망업체의 전산장비 준비 부족 등의 사유로 전자입찰등록
및 투찰이 곤란한 경우 투찰 시간 마감 24시간 이전에 조달청 국가종합전
자조달시스템 또는 전자조달 콜센터(☎ 1588-0800)에 문의해 주시기 바라며
문의를 하지 않아 발생되는 모든 책임은 입찰 참가자에게 있음

위와 같이 공고합니다.

2026년 2월 3일

[수요기관(공기업)] [직위]

문서 유형: 과업지시서
[2026 별바다부산 나이트 마켓 운영 대행]
용역 과업내용서

2026. 2.

담당부서 담당자 연락처 이메일
T)[전화번호]
[부서] 박해경 [이메일]
F)[전화번호]
Ⅰ. 과업개요 및 목표
1. 사 업 명: 2026 별바다부산 나이트 마켓 운영 대행 용역
2. 과업목적: 구포나루축제 연계 지역 대표 야간관광 프로그램 운영
3. 과업기간: 계약일로부터 ~ 2026. 11. 30. 까지
4. 소요예산: 금310,000,000원(금삼억일천만원), 부가가치세 포함
5. 과업 주요 내용
○ 별바다부산 나이트마켓 총괄 기획
○ 프로그램 구성 (얼리 썸머, 골든 어텀에 맞는 프로그램 구성 및 전략 마련)
○ 행사장 조성에 관련된 전반적 업무(행사장 구성 및 공간 배치, 철거 등)
○ 행사 운영 (운영 축제에 필요한 인력, 세부 행사 운영 등)
○ (홍보마케팅) 프로그램별 전반적인 홍보 마케팅 등
○ (안전관리) 행사 운영에 필요한 안전대책, 재난관리 등 비상 대책 수립 등
○ (사업관리) 개인정보 관리, 민원관리, (중간,완료)보고, 만족도 조사 등
6. 성과목표
○ 정량목표
- 축제 총 참여인원: 110,000명 이상(구포나루축제 인원 포함)
- 푸드트럭 7개 이상 (구포나루 축제기간 15개 이상)
- 전통주 10개 이상 섭외(부산기업은 6개 이상)
- 행사 만족도 조사 (참여자, 지역민, 상권) 95점 이상
- 행사 홍보를 위한 키비주얼 및 각종 홍보물 디자인 일체
· 행사 스케치 영상 제작 2건 이상, 현장 사진 촬영 40장 이상
가. 사진: 5600×3700픽셀, 10MB, JPG 기본
나. 영상제작규격: Full HD
※ 영상물 파일(MP4, MOV 등) 형식 등은 상호 협의하여 제출
※ 홍보영상은 1주차에 촬영 후, 편집 후 2주차 전 공사 제출
· 홍보 영상(유튜브, 릴스) 및 썸네일 제작(국, 영, 일, 중)
· 행사홍보 카드뉴스, 웹포스터, 배너등 제작(국, 영, 일, 중)
○ 정성목표
- 별바다부산 나이트 마켓 인지도 제고
- 타지역 국내 관광객 및 국외 관광객 유치 확대
Ⅱ. 과업 세부내용

1. 별바다부산 나이트 마켓 총괄 기획
⁜ 과업 일정 및 테마
행사명(안) 일정(안) 테마 및 필수요건

별바다부산 나이트 마켓 26. 6. 10. ~ 6. 14.
1. (테마) 부산 전통주 팝업 스토어 운영
(얼리 썸머) (5일)
2. (필수) 쿠킹 체험 및 야시장 조성
3. 체험 프로그램(가족단위, 키즈, 힐링) 운영
26. 9. 26. ~27.(2일)
별바다부산 나이트 마켓 4. 트랜디한 맛집 및 플리마켓 업체 섭외
26. 10월 (12일)
(골든 어텀) 5. 구포나루 축제기간(10월) 푸드트럭 섭외 및 운영(15개 이상)
(1~4, 8~11,15~18)

○ 화명생태공원 연꽃단지에 어울리는 전통주 팝업 중심의 야시장 기획
○ 초여름, 가을 시즌으로 운영, 시즌별 어울리는 컨셉 기획
○ 구포나루축제와 어울리는 공간 구성 제안 (구포나루축제10.16. ∼18. / 단일정이변경될수있음)
○ 부산재래시장, 부산 내 음식점 섭외 및 관리
○ 부산 전통주 라인업 구성 및 섭외 관련 업무
○ 트랜디한 로컬 맛집, 타지역 맛집 섭외
○ 유관기관([기관(행정기관)], 낙동강관리본부 등) 및 단체 업무 협조

2. 프로그램 구성
○ (필수 프로그램) 쿠킹 체험 프로그램 제안
- 누구나 참여 가능한 쿠킹 체험 프로그램 기획 및 구성 (즉석 조리, 쿠킹 가능한 메뉴)
- 부산을 대표할 수 있는 음식, 제철 음식으로 메뉴 제안
- 쿠킹 체험 프로그램 운영 방안 제안
○ 야간 체험 프로그램 제안
- 테마가 전통주 팝업스토어이므로, 전통주에 어울리는 프로그램 제안
○ 가족 단위 참여 프로그램 기획 및 제안
- 가족 단위 참여할 수 있는 프로그램으로, 체류시간을 늘릴 수 있도록
체험 프로그램 제안하여 함
- 프로그램은 세대별(타깃별) 참여할 수 있는 프로그램 제안해야 함
○ 부대행사 기획 및 제안
- 전 세대가 즐길 수 있는 부대행사 제안해야 함
- 참여자 확대를 위해 전 세대가 참여할 수 있는 이벤트 구성 및 리워드
굿즈나 경품을 준비해야 함

3. 행사장 조성
○ 행사장 조성에 관한 전반적인 업무
- 장소 여건, 프로그램 특성 등을 고려한 시설물 설치 계획 수립해야 함
- 시설물 설치 전 발주기관과 사전 협의를 반드시 해야 하며, 프로그램 종료
시점에는 즉각 철거하여야 하며, 훼손 발생 시 원상복구 및 정리(청소) 해야 함
- 행사장에 필요한 시설물(무대, 텐트, 플리마켓 매대, 음향 장비, 전기, 조명 등)에
대한 임차, 설치, 관리, 철거 등 전반적인 업무
- 이용자의 불편함이 없도록 편의시설(테이블, 의자, 부대시설 등) 행사에 맞는
제작(임대) 설치 되어야함
- 푸드존(푸드트럭, 맛집), 플리마켓존 외 행사장 내 필수적으로 조성 공간해야 함
(필수: 종합운영본부, 안전관리본부(공사), 의무실, 수유실)
- 행사 장소 내 기본 가로등(조명) 없어, 행사 가능하도록 야간 조명 설치해야 함
(6월 야간경관 조명 없음, 9 ∼ 10월 연꽃단지 주변으로 야간경관 조명 설치 예정)
- 야간 운영으로 통행로 및 대피로 등 고려한 안전한 행사장 조성해야 함
- 지역 특성상 이동용 화장실 설치되어야 하며, 이동식 화장실 전문 임대
하도록 하며, 철저한 운영 관리되어야 함
(이동식 화장실 운반 & 설치, 비품 관리, 화장실 청소, 급수, 오물, 오수 수거 및 처리 등)
- 많은 인파가 이용 예상되는 만큼 충분한 이동용 화장실 임대, 운영되어야 함
- 기간 내 발생되는 쓰레기는 위생적으로 처리될 수 있도록 분류 및 수거,
폐기에 관한 모든 업무
- 에코 클린 스테이션(쓰레기 거점) 설치하여야 하고, 종류별 쓰레기 배출함을
별도 설치하며, 음식물을 버릴 수 있는 배출함을 설치해야 함
- 전통주 판매를 위한 충분한 용량의 냉장시설(업소형 냉장시설) 설치해야 함
- ‘소방 시설 설치 및 관리에 관한 법률’,‘화재예방, 소방시설 설치 및 유지
및 안전관리에 관한 법률’ 적용, 화재 위험 공간에는 소화기 설치
- 그 외 행사장 조성에 필요한 업무를 총괄하고, 책임져야 함
(모든시설물은행사전일설치완료하여야함, 완료후행사준비확인은공사입회하에 1회 이상 하여야 함)
○ 야간 조형물 및 안내 시설물 설치 등
- 기존의 야간경관과 어울리는 포토존을 설치 및 관리
- 설치된 포토존은 공원과 어울리도록 설치되어야 하며, 주변 환경을 해치지
않아야 함
- 포토존은 야간에도 촬영이 가능토록 효과적인 조명 설치되어야 함
- 안전하고, 원활한 행사 안내를 위한 안내판, 현수막 등 시설물 설치 및 철거
- 전기 없는 공간, 동선을 안내할 수 있는 시인성 좋은 안내판 제작 설치
- 야외 안내 시설물은 국, 영문으로 제작되어야 함
- 야간에 진행되는 야외 행사로 인근 주차장 내에도 행사 안내 시설물 설치,
철거하며, 훼손시 최대한 빠르게 원상 복구되어야 함

4. 행사 운영
○ 종합 운영본부 운영 및 운영 인력 배치
- 추진 시기별 행사 로드맵 제시 및 점검
- 분야별 전문 인력 구성, 구성 인력의 단계별 투입 계획 제시하고,
행사기간 동안 반드시 PM(Project Manager) 현장 총괄 관리하여야 함
- 행사 운영 인력은 안전관리 및 비상 대응, 현장 안내, 민원 응대 등에 대한
교육을 실시하여야 함
- 행사 운영 인력은 참여자가 식별할 수 있도록 복장을 갖추어야 함
- 행사 관련 필요한 보험 가입 및 행정 사항 이행
·음식관련 협력사 영업 전 한시적 영업허가 신청 안내 및 확인
- 종합 운영본부에는 외국인 응대가 가능한 인력 배치(영, 일, 중)
- 민원 접수 및 해결
·입점 업체 민원, 고객 민원 발생시 접수, 민원 대응, 처리
· 기타 운영에 필요한 업무 지원 비용 처리 등
○ 부산 전통주, 부산 재래 시장 입점업체(음식) 섭외 및 판매 등 원활한 운영 관리
- 부산에서 생산되는 전통주업체 섭외하고, 판매될 수 있도록 협의
- 부산 외 타지역의 전통주 업체 섭외할 수 있어야 하며, 협업 제안
- 부산 전통주 판매를 위한 냉장 시설, 판매대, 판매인원 총괄 관리
- 전통주 원활한 판매를 위한 공동판매부스 운영하며, 수급을 책임져야 함
- 부산 지역 시장 내 입점 업체(간이 음식점업, 한식 음식점업)를 섭외하고,
판매할 수 있도록 협의·조정하여 최대한 판매할 수 있도록 해야 함
○ 다양한 푸드트럭 섭외하고 선정 및 전반적인 총괄 운영
- 기간 내 다양한 푸드트럭이 섭외하며, 종류가 겹치지 않도록 함
- 구포 나루 축제 기간은 최소 15개 이상, 다른 기간 내 7개 이상 확정 섭외
- 구포나루 축제 기간 동안 푸드트럭 섭외에 대한 모든 권한을 갖음
- 축제 기간 내 푸드트럭 운영시간은 11:00 ~ 21:00 운영 조정 해야함
- 많은 인원이 이용하기에 불편함이 없도록 편의시설사 및 푸드트럭
모집 및 선정, 철저한 위생 운영 관리·감독
- 구포나루 축제기간 동안 푸드트럭 운영할 수 있는 충분한 전기공급을
위해 [기관(행정기관)]과 사전 조율 협의하도록 하며, 그 외 기간에도 푸드트럭 운영할
수 있는 충분한 전기 공급 방안을 마련
○ 기업, 민간 협업 및 외부 단체 협력 방안 제시
- 부산 유관기관 협력 방안 및 부산 내·외 협력사 참여 확대 방안 제시
- 부산(재래시장) 내 맛집 섭외 및 영업 협의

5. 홍보 마케팅
○ 전략적인 홍보마케팅 전략 수립
- 참여자 모객 및 행사 이슈화를 위한 홍보마케팅 계획 수립 및 제안
- 추진 시기별 홍보 로드맵 제시 및 이행
- 행사 홍보를 위한 외부 광고 채널 활용 홍보 제안
·예) 라디오, 외부 광고, 언론보도, 인플루언서 등
○ 온·오프라인 홍보 콘텐츠 제작
- 행사 홍보를 위한 키비주얼 및 각종 홍보물 디자인 작업 일체
· 카드뉴스, 배너, 행사 영상 릴스, 숏폼 제작 및 업로드
(국, 영, 일, 중)
· 공사 홍보채널(visit Busan/Starrynightbusan) 활용, 제작 어권
- 축제를 알릴 수 있는 오프라인 홍보 (어권: 국, 영, 일, 중)
· 인근지역 광고 배너 제작 및 부착, 철거 등
· 행사를 알릴 수 있는 홍보물, 안내물, 현장 안내물 제작
① 모든 제작물은 키비주얼 활용, 가독성과 시인성 확보
(먼거리에도 확인 가능, 안내 문구가 잘 확인되는지, 야간에도 식별이 가능하도록)
② 안내 POP(진입 유도, 관람 편의 고려, 사인물) 제작
③ 사전 행사 안내를 위한 현수막 제작 및 철거(주차 안내, 행사 안내)
(강풍 및 폭우로 인한 사인물 파손으로 안전사고가 발생하지 않도록 고정장치 필수)
⑤ 국외 관광객 안내 및 편의를 위해 다국어로 제작
⑥ 축제 기간 중 현장 안전 총괄 담당자 연락처는 필수적으로 부착(공원 내)
○ 행사 고화질 사진, 영상 등을 촬영 및 제출 (원본파일)

6. 안전관리
○ 안전관리 계획 수립 및 실행
- 행사 준비 전 안전대책계획(지역 안전심의위원회) 수립 및 이행
- 응급상황 발생 대비 방안 마련 및 응급처치 전문인력(응급구조사), 구급차
(운전기사 포함) 배치
- 현장 안전사고 및 재해예방을 위한 안전관리자의 선임
- 안전관리자 [담당자] 제출 및 안전교육일지, 점검일지 작성·제출
(제출서류 양식 추후 제공, 안전점검일지 내 위험성 평가 실시 및 결과 내용 필히 포함)
- 행사 안전 보험 가입 및 서류 제출
- 천재지변 및 기상악화 시 비상 대책 수립 및 시행 등
·우천, 강풍, 폭염 등 기상 상황에 따른 행사 운영 방안 마련
- 설치, 철거 단계별 안전 방침 및 체크리스트 마련하여 적용하며
행사 준비 전에 체크리스트 공사에 제출
- 작업 및 근무 인력의 안전사고 발생 방지 노력, 대처 방안 등 마련
7. 사업관리(개인정보, 만족도 조사, 보고 등)
○ 행사 참여자 대상 만족도 조사 및 효과 분석
- 방문객 대상 프로그램 등에 대한 만족도 조사 실시하고 효과 분석 제시
- 설문조사 로우데이터 제출, 결과 보고시 반영
○ 이벤트 진행할 경우 개인정보 수집 시 개인정보 관리
- 프로그램 참가 및 이벤트 당첨 안내
· (고지) 프로그램 참가 신청시 주체, 목적, 파기 시기등 고지 필수
· 수집한 개인정보는 목적을 위해서만 사용되어야 하며, 목적 외 사용 및
제 3자 노출 등으로 인한 윤리적·법적 책임은 과업 수행자에게 있음
· 프로그램 종료 후 즉시 파기
○ 프로그램 결과 및 관련 서류 제출
- 세부 프로그램에 대한 중간, 완료 보고는 서류로 제출
- 공사 요청 시 착수, 중간, 중간 완료, 완료보고회 개최
· 행사 실시 최소 10 일전 최종 점검 실사 시행 , 최종 점검 후 보완
· 업무 수행 방법이나 잠재적 위험 요소 발생시 조치 방안 논의 및 처리 후 보고
· 공사 요청 시 서면 또는 대면보고
- 전체 행사 종료 후 최종 결과 보고 제출
· 최종 결과 보고는 행사 종료 후 30일 이내 제출

Ⅲ. 과업 일반지침

1. 용어의 정의
가. “발주자”이라 함은 [수요기관(공기업)]를 말한다.
나. “계약상대자”라 함은 본 계약을 체결한 수급인을 말한다.
2. 주요업무의 사전승인
가. 계약상대자는 다음 사항에 대해 발주자와 사전 협의 후 과업을 수행하여야 한
다.
1) 과업수행계획서 및 과업내용 변경 등을 포함한 자료 제출
2) 용역수행자의 교체
3) 기타 용역감독자의 요청이나 계약상대자의 판단에 따라 승인 받아야 할 사항
3. 과업수행기준
가. 계약상대자는 과업내용서와 관계 법령 및 각종 규정 등에 따라 성실하게 과업
을 수행하여야 한다.
나. 계약상대자는 다음에 대하여 발주자와 협의하여 반영 할 수 있다.
1) 과업내용서에 명기되지 않은 사항으로서 본 과업과 관련하여 발주기관과 협
의하여 결정하여야 할 사항
2) 발주기관의 사정에 의하여 불가피하게 내용을 변경이 필요한 사항
3) 기타 과업수행과 관련하여 계약상대자가 단독으로 결정하기 곤란한 사항
다. 계약상대자는 원활한 과업 수행을 위해 필요한 경우 관련 전문가 등의 자문을
구할 수 있으며, 비용은 계약상대자가 부담한다.
라. 과업 진행 및 세부 내용 검토 등을 위해 발주기관의 요구가 있을 때 필요한
자료 제출을 하여야 한다.
마. 본 과업수행 목적으로 사용한 각종 기준과 모든 공식자료 및 통계는 근거가
명확하고 객관적으로 인정되는 최신 자료를 이용하여야 하며 서면으로 그 근
거를 제시해야 한다.
바. 본 과업수행에 있어 과업 내용 및 기간의 변경이나 범위를 조정할 필요가 있
는 경우에는 계약상대자와 발주기관과 상호 협의하여 결정한다.
사. 본 과업의 수행과정에서 계약 당시 예상하지 못한 사항으로써 과업수행 상 반
드시 필요하다고 발주기관이 인정하는 추가 과업이 발생한 경우 계약금액 및
기간 등 계약 내용을 변경할 수 있다.
아. 과업 완료일 기준 과업 달성률이 90% 미만일 경우 미달한 비율만큼 사업비에
서 정산한다. 다만 본 과업수행 중 부득이한 사유로 당초 계획대로 수행이
어려운 경우에는 발주기관의 사전 승인을 얻어 과업 및 보고 기간 등을 연장
하거나 조정할 수 있다.
(달성률에 대한 판단은 발주부서 감독관(담당자)가 해당 과업내용서에 따른 과
업량과 산출내역서에 따른 지출금액을 종합하여 판단)
자. 계약상대자는 성과품 납품 후에도 발주기관이 자문을 요청할 경우 이에 성실
히 응하여야 하며, 각종 행정절차 등의 이행이 완료되어야 본 과업이 완료된
것으로 본다.
차. 착수계 제출
1) 계약상대자는 계약문서에 정하는 바에 따라 용역을 착수하여야 하며, 착수
시 관계법령 등에서 정한 서류 및 다음 각 호의 사항을 포함하여 착수계를
제출하여야 한다.
가) 착수신고서(책임연구원 선임계(이력첨부), 예정공정표, 과업수행전담조직표 등)
나) 분야별 참여기술자 및 장비 투입 계획서
다) 기타 용역수행에 필요한 서류(발주자 또는 법령이나 과업에 제출하도록
기재한 사항 등)
2) 과업수행계획서 제출
착수계 제출 시 과업 특성 및 여건 등을 감안한 과업수행계획서를 제출하여
발주처에 승인을 받아야 하며, 이에 포함될 내용은 다음과 같다.(공동수급일
경우 공동수비인 상호간의 과업 분할협의서 첨부)
가) 세부 공정계획서
나) 과업의 단계별 성과품 제출계획서
다) 과업수행 조직 및 인력(장비) 투입 계획서
라) 참여연구진 경력사항 확인서
마) 참여기술자 인적사항, 참여하고 있는 과업내용 및 예상기간
바) 참여기술자의 보안대책 및 보안각서
3) 계약상대자는 계약의 이행 중에 과업내용의 변경 등으로 인하여
“1)”,“2)” 에 따라 제출한 서류의 변경이 필요한 때에는 관련서류를 변경
하여 제출해야 한다.
카. 공정보고
1) 계약상대자는 발주처의 요구가 있거나 아래의 경우 발주처에 사전 보고 하여
야 하며, 책임기술자로 하여금 설명하도록 하여야 한다.
가) 용역착수단계, 중간단계, 마무리단계 검토, 자문회의, 기타 발주청의 요청이
있는 경우
나) 과업수행방향 및 방법, 세부 수행계획 등 과업수행에 필요한 사항
2) 발주처와 협의하여 공정보고는 서면으로 대체할 수 있다.
타. 용역 감독 등
1) 원활한 과업 수행을 위해 발주처는 계약상대자에 대해 정기 또는 수기 점검
을 실시 할 수 있다.
2) 계약상대자는 특별한 사유가 없는 한 응해야 하며, 지적사항 발생 시 발주처
와 협의하여 시정하여야 한다.
파. 성과품 제출
1) 성과품의 편집은 발주처와 협의하여 작성하고, 납품목록 및 주요 성과품을
제출하기 전에 각 1부를 제출하여 확인을 받아야 하며, 확인과정에서 지적
되는 사항은 즉시 수정하여 최종 성과품을 제출하여야 한다.
2) 성과품 규격 및 작성기준
가) 용지규격은 A4(210mm × 297mm)로 한다.
나) 보고서 작성은 한글, 아라비아 숫자, 미터법을 원칙으로 하며, 한문 또는
영문 등의 표기가 필요한 경우에는 한글과 병기하여 수록하여야 한다.
다) 보고서는 평가 내용을 함축적으로 표현하도록 한다.
라) 보고서의 내용은 가급적 도표와 그림을 삽입하여 이해 효과를 높일 수 있
도록 한다.
바) 보고서 등 모든 성과품은 전자파일 형태로 작성･제출한다.
3) 성과품 제출목록
구분 성 과 품 수량 비고
보고서 o 용역 종합 결과보고서

o 이벤트 진행시 신청자 및 참가자 명단
(확인 서명 날인 또는 모바일 집계)
o 만족도 조사 설문지 원본 및 결과보고
- 참여자 프로그램 만족도 조사 (로우데이터 포함)
o 행사현장 촬영 기록물(영상, 사진 등)
- 영상은 클린본, 편집본 분리 제출
- 사진은 편집 및 보정된 사진 제출 전자파
2식
기타 o 각종 디자인 최종시안(ai,psd,pdf,png,jpeg) 일

o 세부사업별 안전교육 자료 및 사진자료

o 총사업비 세부 정산 내역서
(세부 사업별 정산 내역서 포함)
- 지출 증빙 서류(세금계산서 등)

o 기타 공사의 사업 수행 및 종료를 위해
필요한 자료 일체

Ⅳ. 계약조건

1. 적용범위
가. 본 과업내용서는 「2026 별바다부산 나이트 마켓 운영」 용역을 수행하기 위
한 제반 사항을 규정하며, 여기에 규정되지 않은 사항은 『지방계약법령』,
「지방자치단체 입찰 및 계약 집행기준」및 기타 관련 법규에서 규정한 것을
따르고, 상호협의가 필요한 사항은 [수요기관(공기업)](이하 “공사”라 한다.)와 사
전 협의하여야 한다.
2. 법규준수
가. 계약상대자는 과업 수행 시 관련 법규의 규정을 준수하여 법 위반이 발생하
지 않도록 한다.
나. 계약상대자는 과업 수행 중에 관련 법규가 변경되고 변경된 규정에 따라야
할 경우 공사와 협의하여 새로운 법령의 규정을 우선하여 준수하여야 한다.

3. 착수와 보고
가. 계약상대자는 계약문서에서 정하는 바에 따라 과업에 착수해야하며, 착수 시
에는 관련법령에서 정한 서류와 공정예정표, 인력 및 장비투입계획서, 보안
서약서 등을 포함한 착수신고서를 발주기관에 제출해야 한다.
나. 계약상대자는 계약의 이행 중에 과업내용의 변경 등으로 인하여 착수신고서
등 제출한 서류의 변경이 필요한 대에는 관련서류를 변경하여 제출해야 한
다.
다. 공사 담당자는 과업의 전부 또는 일부의 진행이 지연되어 정한 기간 안에
수행이 불가능하다고 인정되는 경우에는 주간공정 현황을 제출토록 하는 등
계약상대자에게 필요한 조치를 할 수 있다.

4. 근로자에 대한 책임과 의무
가. 계약상대자는 해당계약의 시공·관리 및 계약이행에 필요한 기술과 경험을 가
진 근로자를 채용해야 하며 근로자의 행위에 대하여 모든 책임을 져야 한다.
나. 공사 담당자는 계약상대자가 채용한 근로자가 「지방자치단체 입찰 및 계약
집행기준」 제9장 계약 일반조건에서 정한 사유에 해당한다고 판단될 경우
해당 근로자의 교체를 요청할 수 있다.
다. 계약상대자는 근로자의 교체 요청을 받은 경우 공사와 협의하여 교체여부를
결정하여야 한다.
라. 계약상대자는 해당 계약의 이행을 위하여 채용한 근로자에 대하여『최저임금
법』제6조제1항·제2항과 『근로기준법』제43조를 준수해야 한다.
마. 계약상대자는 계약문서에서 별도로 정하고 있지 아니하는 한 공사 담당자의
필요에 따른 경우를 제외하고는 휴일·야간작업을 할 수 없다.
바. 계약상대자는 공사 담당자와 협의하여 휴일·야간작업을 하는 경우에는 추가
비용을 청구할 수 없다. 다만, 공사 담당자의 기간 단축 지시나 공사의 부득
이한 사유로 인하여 휴일·야간작업을 지시한 때에는 그러지 아니한다.

5. 과업내용 변경 및 계약금액 조정
가. 공사 담당자는 계약의 목적상 필요하다고 인정될 경우에는 다음 각 호의 과
업내용을 계약상대자에게 지시할 수 있다.
1) 추가업무 및 특별업무의 수행
2) 용역공정계획의 변경
3) 특정용역 항목의 삭제 또는 감소
나. 위에 따른 과업내용의 변경은 그 변경이 필요한 부분의 이행 전에 완료해야
한다. 다만, 공사 담당자는 계약이행의 지연으로 품질 정하가 우려되는 등
긴급하게 용역을 수행해야 할 필요가 있을 때에는 계약상대자와 협의하여
그 변경시기 등을 명확히 정하고, 과업내용의 변경을 완료하기 전에 우선용
역을 이행하게 할 수 있다.
다. 계약상대자는 계약의 기본방침에 대한 변동 없이 과업내용서의 과업내용을
변경함으로써 공사에 유리하다고 판단될 경우 위 1)~3)에 해당하는 제안을
할 수 있다.
라. 공사 담당자는 용역 과업내용의 변경을 지시하거나 승인한 경우에 계약금액
조정은 다음 각 호의 어느 하나에 해당하는 기준에 따라 계약금액을 조정해
야 한다.
1) 증감된 과업량의 단가는 계약단가로 한다. 다만, 계약단가가 예정가격단가
보다 높은 경우로서 물량이 증가하게 되는 경우 그 증가된 물량에 대한 적
용단가는 예정가격단가로 한다.
2) 산출내역서에 없는 품목·비목의 단가는 과업변경 당시를 기준으로 산정한
단가를 기준으로 한다.
3) 공사가 과업변경을 요구한 경우 증가된 과업량이나 신규 비목의 단가는 과
업변경 당시 산정한 단가를 기준으로 하여 공사와 계약상대자가 서로 주장
하는 각각의 단가기준에 대한 근거자료 제시 등을 통하여 성실히 협의하여
결정한다.
6. 지연배상금
가. 계약상대자는 계약서에 정한 기한 안에 계약을 완료하지 아니한 때에는 매
지체 일수(법정공휴일, 일요일 포함)마다 계약서에 정한 지연배상금률을 계약
금액에 곱하여 산출한 금액을 현금으로 납부해야 한다. 다만, 지연배상금이
계약금액의 100분의 30을 초과하는 경우 100분의 30으로 한다.
나. 공사 담당자는 지연배상금을 부과하는 경우 기성부분에 대하여 검사를 거쳐
이를 인수하거나 관리·사용하는 있는 때에는 그 부분에 상당하는 금액을 계
약금액에서 공제한다. 이 경우 기성부분의 인수는 그 성질상 분할 할 수 있
는 용역에 대한 완성부분으로 인수하는 것에 한한다.

7. 계약기간의 연장
가. 계약상대자는 다음 사유가 발생했을 경우에는 공사 담당자와 협의하여 과업
기간을 조정 할 수 있다.
1) 불가항력적인 사유가 발생하였을 때
2) 공사의 책임으로 용역 착수가 지연되거나 용역수행이 중단된 경우
3) 계약상대자의 부도 등으로 용역 보증기관이 보증이행업체를 지정하여 보증
이행할 경우
4) 과업내용 변경으로 인하여 계약기간 안에 계약을 이행할 수 없을 경우
5) 그 밖에 계약상대자의 책임에 속하지 않는 사유로 인하여 지체된 경우
나. 이 경우 계약상대자는 지체 없이 공사 담당자에게 수정공정표를 첨부하여
서면으로 계약기간의 연장을 청구해야 한다. 다만, 연장사유가 계약기간 안
에 발생하여 계약기간을 지나서 종료된 경우에는 그 사유가 종료된 후 즉시
계약기간의 연장을 청구해야 한다.

8. 계약의 해지 등
가. 공사는 다음과 같은 행위가 발생하였을 때 특별한 사유가 없는 한 계약 위
반행위로 간주하여 계약조건의 규정에 따라 해지(해제) 등 조치할 수 있다.
1) 계약상대자의 책임 있는 사유로 인하여 완료 기한까지 용역을 완료하지 못
하거나 완료할 가능성이 없다고 인정될 경우
2) 계약상대자가 정당한 이유 없이 공사 담당자의 이행 촉구에 따르지 아니한 경우
3) 계약 이행 과정에서 관계 직원 등에게 직접 또는 간접적으로 사례, 증여, 금
품·향응 제공을 하는 등 청렴서약서 내용을 위반한 경우
4) 계약상대자의 부도, 파산, 해산, 영업정지, 사업 또는 영업에 관한 등록·인가·
허가 등의 취소, 그 밖의 사유로 계약 이행이 곤란하다고 인정되는 경우
5) 제안한 업체(전통주, 푸드트럭, 구포소상공인, 플리마켓)섭외되지 않을 경우,
순위 협상자(계약자)라고 하더라도, 협상(계약)은 결렬(해지)되며, 이에 이의

제기를 할 수 없음

9. 지식재색권 등 저적권등
가. 과업 수행에 따른 결과물의 지식재산권은 공동으로 소유하며, 그 지분은 균
등하게 한다. 그 외 과업 수행과 관련한 산출물 일체에 대한 권한은 공사에
있다. 단, 결과물 중에서 용역수행자가 용역 수행을 위해 활용한 용역 수행자
의 고유 자료에 대한 소유권 ․ 저작원 ․ 특허권 ․ 상표권 ․ 실용신안권 ․ 기타 지적
재산권에 대한 일체의 권리(2차적 저작물 또는 편집저작물을 작성하여 이용할
권리를 포함한다)는 공사에 귀속되지 아니함
나. 계약상대자는 과업 수행 과정에서 활용하는 모든 콘텐츠의 저작권, 디자인권, 특허권, 상표
권 등 제3자의 지적재산권이 침해되지 않도록 사전 확인해야 하고, 필요시 사용권을 확보한
후 사용해야 한다. 이때 필요한 조치를 이행하지 아니하여 발생하는 민·형사상 책임은
계약 상대자에게 있음
다. 계약상대자는 용역 결과물 및 과업 수행과 관련한 산출물의 배포 또는 복제가 필
요한 경우 공사와 사전 협의하여야 하며, 공사는 보안 등 특수성이 있는 경우 해당 결
과물·산출물의 배포 또는 복제를 제한할 수 있다.
라. 본 사업을 위하여 공사가 제공한 자료와 수행 중 처리·발생된 자료는 사업이 끝나는 즉시 정
리하여 반납하여야 하며 , 취득 및 반환 시 공사의 승인을 받아야 한다.

10. 안전·보건 확보 의무 이행
가. 계약상대자는 과업을 수행함에 있어서 현장 안전 관리자 및 이용자의 안전을
확보하기 위하여 안전보건 관계법령 및 중대재해처벌법 상 의무 사항을
반드시 이행하고, 의무사항을 이행하지 않아 중대산업재해가 발생할 경우
그에 따라 발생하는 법적 처벌 및 공사의 불이익 조치에 대해서 이의를
제기하지 않는다.
나. 계약상대자의 귀책 사유로 인하여 사고 발생 시 이에 대한 책임은 계약
상대자가 진다.

###  각 v 항목의 대표 공고를 확인여 어떤 공고에서 1이 되는 지 파단

In [43]:
for i in range(1, 25):
    col = f"v{i}"
    rows = labels[labels[col] == 1]

    if len(rows) > 0:
        print(col, "대표 ID:", rows.iloc[0]["id"])

v1 대표 ID: PPS-DEV-01
v2 대표 ID: PPS-DEV-02
v3 대표 ID: PPS-DEV-04
v4 대표 ID: PPS-DEV-06
v5 대표 ID: PPS-DEV-07
v6 대표 ID: PPS-DEV-08
v7 대표 ID: PPS-DEV-09
v8 대표 ID: PPS-DEV-05
v9 대표 ID: PPS-DEV-09
v10 대표 ID: PPS-DEV-13
v11 대표 ID: PPS-DEV-14
v12 대표 ID: PPS-DEV-15
v13 대표 ID: PPS-DEV-16
v14 대표 ID: PPS-DEV-17
v15 대표 ID: PPS-DEV-18
v16 대표 ID: PPS-DEV-20
v17 대표 ID: PPS-DEV-21
v18 대표 ID: PPS-DEV-22
v19 대표 ID: PPS-DEV-23
v20 대표 ID: PPS-DEV-24
v21 대표 ID: PPS-DEV-25
v22 대표 ID: PPS-DEV-26
v23 대표 ID: PPS-DEV-27
v24 대표 ID: PPS-DEV-29

#### 대표 사례의 정답 근거 문장만 한 번에 확인

In [44]:
for i in range(1, 25):
    col = f"v{i}"
    rows = labels[labels[col] == 1]

    if len(rows) > 0:
        row = rows.iloc[0]
        evidence = row[f"e{i}"]

        print(f"\n[v{i}] {row['id']}")
        print("근거:", evidence)

[v1] PPS-DEV-01
근거: 라. 본 용역은 「고등교육법」 제2조에 따른 대학 또는 「산업교육진흥
및 산학연협력촉진에 관한 법률」 제25조에 따른 산학협력단만 참여 가능함

[v2] PPS-DEV-02
근거: 외국 학술지 공급계약을 3천만원 이상 체결한 실적이 있는 자

[v3] PPS-DEV-04
근거: 공고일 기준 최근 5년 간 단일 건으로 455,000,000원 이상(기초금액의 130% 이상)의 해양탐사 또는 수중조사 또는 침몰선박 조사·확인작업 분야 각종 작업 1건 이상 수행실적을 실적증명서로 제출이 가능한 업체

[v4] PPS-DEV-06
근거: 다. 최근 5년간 국가기관이 발주한 국제회의 개최 대행 용역의 이행실적이 4억원 이상인 업체

[v5] PPS-DEV-07
근거: 마. 본사(주된 영업소)의 소재지가 서울특별시에 있는 업체

[v6] PPS-DEV-08
근거: 라. 입찰공고일 전일부터 계약체결일까지 주된 영업소가 서울특별시 [지역:r1|단위=기초|광역=서울특별시] 내에 소재하고 있는 업체이어야 합니다.

[v7] PPS-DEV-09
근거: 마. 주된 영업소(본사 소재지를 말함)가 입찰공고일 현재 광주광역시, 전라남도의 관할구역 안에 있어야 합니다.

[v8] PPS-DEV-05
근거: 입찰공고일 전일 현재 제주특별자치도에 법인등기부상 본점 소재지(개인사업자인 경우에는 사업자등록증 또는 관련 법령에 따른 허가·인가·면허·등록·신고 등에 관련된 서류에 기재된 사업장의 소재지)를 두고 당해자격을 입찰일(낙찰자는 계약체결일)까지 유지하고 있는 업체로서 다음 각호의 자격을 모두 충족하여야 합니다.

[v9] PPS-DEV-09
근거: Chipset: GB10 Grace Blackwell Superchip

[v10] PPS-DEV-13
근거: nan

[v11] PPS-DEV-14
근거: nan

[v12] PPS-DEV-15
근거: 마. 본 입찰 대상 물품(과일류, 세부품명번호 5030990101)에 대한 직접생산확인증명서를 보유한 자이어야 합니다.

[v13] PPS-DEV-16
근거: 『중소기업제품 구매촉진 및 판로지원에 관한 법률』 제2조에 따른 소기업자로서 중소기업 범위 및 확인에 관한 규정에 따라 발급된 소기업, 소상공인확인서를 소지한 업체이어야 합니다(『소기업·소상공인 확인서』는 중소기업공공구매 종합정보망에서 확인하며, 확인이 되지 않을 경우 입찰 참가 자격이 없습니다.)

[v14] PPS-DEV-17
근거: 다. 「중소기업기본법」제2조에 따른 중소기업자 또는 「소상공인 보호 및 지원에 관한 법률」제2조에 따른 소상공인으로서 중소기업확인서를 소지한 업체이어야 합니다.

[v15] PPS-DEV-18
근거: 소기업·소상공인 확인서는 입찰서 제출마감일 전일까지 발급된 것으로 유효기간 내에 있어야 하며, 중소기업제품 공공구매 종합정보망(http://www.smpp.go.kr)에서 확인이 안될 경우 입찰참가자격이 없습니다.

[v16] PPS-DEV-20
근거: nan

[v17] PPS-DEV-21
근거: 다. 「중소기업기본법」제2조에 따른 중소기업 또는 「소상공인 보호 및 지원에 관한 법률」제2조에

[v18] PPS-DEV-22
근거: nan

[v19] PPS-DEV-23
근거: 본 사업은 물품제조사(공급사)·기술지원사의 물품공급·기술지원이 필요한 사업으로 첨부된 물품공급·기술지원협약서 내용을 확인 후 입찰 참가하시기 바라며, 입찰 참가자는 제조사(공급사)·기술지원사로부터 물품공급·기술지원 확약서를 전자입찰서 제출 마감일 전까지 보유하여야 하고, 계약 시 제출해야 합니다.

[v20] PPS-DEV-24
근거: nan

[v21] PPS-DEV-25
근거: 2) 공동수급(공동이행방식)을 허용하며, 공동수급 참여자(구성원)는 조달청 입찰참가자격을 충족하여야 한다. 공동수급체 구성원은 주사업자(대표자)를 명시한 공동협정서를 반드시 제출하여야 하며, 대표[담당자] 지분참여 비율이 많은 업체로 한다. (최소 지분율 3% 이상)

[v22] PPS-DEV-26
근거: 발주기관이 개최하는 사업설명회에 참석한 자(설명회 일정은 추후 안내)

[v23] PPS-DEV-27
근거: 마. 사업설명회 : 2026. 2. 3.(화) 14:00, [시설명] 자연교육센터 2층

[v24] PPS-DEV-29
근거: 나. 용역금액: 금37,930,000원(추정가격 34,481,818원, 부가가치세 3,448,182원)

### 표로 정리하는 단계입니다.

In [ ]:
summary = []

for i in range(1, 25):
    col = f"v{i}"
    rows = labels[labels[col] == 1]

    if len(rows) > 0:
        row = rows.iloc[0]
        summary.append({
            "항목": col,
            "항목명": item_table["항목"][col]["항목명"],
            "대표 ID": row["id"],
            "근거": "" if pd.isna(row[f"e{i}"]) else row[f"e{i}"]
        })

summary_df = pd.DataFrame(summary)
pd.set_option("display.max_colwidth", None) # 긴 문장 자동으로 줄여서 보여줌
summary_df

,항목,항목명,대표 ID,근거
0,v1,참가자격 특정기관 제한,PPS-DEV-01,라. 본 용역은 「고등교육법」 제2조에 따른 대학 또는 「산업교육진흥\n및 산학연협력촉진에 관한 법률」 제25조에 따른 산학협력단만 참여 가능함
1,v2,고시금액 미만 실적제한,PPS-DEV-02,외국 학술지 공급계약을 3천만원 이상 체결한 실적이 있는 자
2,v3,실적제한 1배수 이상,PPS-DEV-04,"공고일 기준 최근 5년 간 단일 건으로 455,000,000원 이상(기초금액의 130% 이상)의 해양탐사 또는 수중조사 또는 침몰선박 조사·확인작업 분야 각종 작업 1건 이상 수행실적을 실적증명서로 제출이 가능한 업체"
3,v4,"고시금액 이상 특정기관, 특정실적",PPS-DEV-06,다. 최근 5년간 국가기관이 발주한 국제회의 개최 대행 용역의 이행실적이 4억원 이상인 업체
4,v5,고시금액 이상 지역제한,PPS-DEV-07,마. 본사(주된 영업소)의 소재지가 서울특별시에 있는 업체
5,v6,"고시금액 미만 지역제한 시,군,구",PPS-DEV-08,라. 입찰공고일 전일부터 계약체결일까지 주된 영업소가 서울특별시 [지역:r1|단위=기초|광역=서울특별시] 내에 소재하고 있는 업체이어야 합니다.
6,v7,고시금액 미만 지역제한 인접 확대,PPS-DEV-09,"마. 주된 영업소(본사 소재지를 말함)가 입찰공고일 현재 광주광역시, 전라남도의 관할구역 안에 있어야 합니다."
7,v8,중복제한 (실적+지역),PPS-DEV-05,입찰공고일 전일 현재 제주특별자치도에 법인등기부상 본점 소재지(개인사업자인 경우에는 사업자등록증 또는 관련 법령에 따른 허가·인가·면허·등록·신고 등에 관련된 서류에 기재된 사업장의 소재지)를 두고 당해자격을 입찰일(낙찰자는 계약체결일)까지 유지하고 있는 업체로서 다음 각호의 자격을 모두 충족하여야 합니다.
8,v9,과업지시서 특정 모델명 명시,PPS-DEV-09,Chipset: GB10 Grace Blackwell Superchip
9,v10,중기간 경쟁제품 입찰 직생 없음,PPS-DEV-13,
10,v11,중기간 경쟁제품 입찰 중소 없음,PPS-DEV-14,
11,v12,일반제품 직생 제한,PPS-DEV-15,"마. 본 입찰 대상 물품(과일류, 세부품명번호 5030990101)에 대한 직접생산확인증명서를 보유한 자이어야 합니다."
12,v13,"중기간 경쟁제품 소기업, 소상공인 제한",PPS-DEV-16,"『중소기업제품 구매촉진 및 판로지원에 관한 법률』 제2조에 따른 소기업자로서 중소기업 범위 및 확인에 관한 규정에 따라 발급된 소기업, 소상공인확인서를 소지한 업체이어야 합니다(『소기업·소상공인 확인서』는 중소기업공공구매 종합정보망에서 확인하며, 확인이 되지 않을 경우 입찰 참가 자격이 없습니다.)"
13,v14,고시금액 이상 일반물품 중소기업 제한,PPS-DEV-17,다. 「중소기업기본법」제2조에 따른 중소기업자 또는 「소상공인 보호 및 지원에 관한 법률」제2조에 따른 소상공인으로서 중소기업확인서를 소지한 업체이어야 합니다.
14,v15,1억 이상- 고시금액미만 소기업 제한,PPS-DEV-18,"소기업·소상공인 확인서는 입찰서 제출마감일 전일까지 발급된 것으로 유효기간 내에 있어야 하며, 중소기업제품 공공구매 종합정보망(http://www.smpp.go.kr)에서 확인이 안될 경우 입찰참가자격이 없습니다."
15,v16,1억 이상- 고시금액미만 중소기업 제한 없음,PPS-DEV-20,
16,v17,1억원 미만 일반물품 중소기업 제한,PPS-DEV-21,다. 「중소기업기본법」제2조에 따른 중소기업 또는 「소상공인 보호 및 지원에 관한 법률」제2조에
17,v18,1억원 미만 일반물품 소기업 제한 없음,PPS-DEV-22,
18,v19,물품공급 확약서 입찰 시 제출,PPS-DEV-23,"본 사업은 물품제조사(공급사)·기술지원사의 물품공급·기술지원이 필요한 사업으로 첨부된 물품공급·기술지원협약서 내용을 확인 후 입찰 참가하시기 바라며, 입찰 참가자는 제조사(공급사)·기술지원사로부터 물품공급·기술지원 확약서를 전자입찰서 제출 마감일 전까지 보유하여야 하고, 계약 시 제출해야 합니다."
19,v20,입찰참가자격 (SW),PPS-DEV-24,
20,v21,공동 5% (10%),PPS-DEV-25,"2) 공동수급(공동이행방식)을 허용하며, 공동수급 참여자(구성원)는 조달청 입찰참가자격을 충족하여야 한다. 공동수급체 구성원은 주사업자(대표자)를 명시한 공동협정서를 반드시 제출하여야 하며, 대표[담당자] 지분참여 비율이 많은 업체로 한다. (최소 지분율 3% 이상)"
21,v22,현장설명회 참석업체 (자격으로 제한 여부) * 계약방법 협상만 적용,PPS-DEV-26,발주기관이 개최하는 사업설명회에 참석한 자(설명회 일정은 추후 안내)
22,v23,현장설명회 (공고기간) * 계약방법 협상 + 계약법 지방만 적용,PPS-DEV-27,"마. 사업설명회 : 2026. 2. 3.(화) 14:00, [시설명] 자연교육센터 2층"
23,v24,공고서와 나라장터 입력값 상이,PPS-DEV-29,"나. 용역금액: 금37,930,000원(추정가격 34,481,818원, 부가가치세 3,448,182원)"

 ### v1~v3의 정확한 항목 정의를 확인

In [12]:
with zipfile.ZipFile(ZIP_PATH) as z:
    for name in z.namelist():
        if name.endswith(".json"):
            print(name)

data/정답스키마_디코딩.json
data/항목표.json

### 항목표.json에서 v1~v24의 기준을 확인

In [15]:
for code, info in item_table["항목"].items():
    print(f"{code}: {info['항목명']}")
    print(f"  부재탐지: {info['부재탐지']}")
    print(f"  비고: {info['비고']}")
    print()

v1: 참가자격 특정기관 제한
  부재탐지: False
  비고:

v2: 고시금액 미만 실적제한
  부재탐지: False
  비고: 지방 + 소액수의 가능

v3: 실적제한 1배수 이상
  부재탐지: False
  비고: 사업예산 기준

v4: 고시금액 이상 특정기관, 특정실적
  부재탐지: False
  비고: 특정기관 표현 다양

v5: 고시금액 이상 지역제한
  부재탐지: False
  비고: 지방, 지자체에 따라 고시금액 다름

v6: 고시금액 미만 지역제한 시,군,구
  부재탐지: False
  비고: 지방 + 소액수의 가능

v7: 고시금액 미만 지역제한 인접 확대
  부재탐지: False
  비고: 지방 + 소액수의 가능

v8: 중복제한 (실적+지역)
  부재탐지: False
  비고: 지방 + 소액수의 가능

v9: 과업지시서 특정 모델명 명시
  부재탐지: False
  비고:

v10: 중기간 경쟁제품 입찰 직생 없음
  부재탐지: True
  비고:

v11: 중기간 경쟁제품 입찰 중소 없음
  부재탐지: True
  비고:

v12: 일반제품 직생 제한
  부재탐지: False
  비고: 중기간경쟁제품 고시 참고

v13: 중기간 경쟁제품 소기업, 소상공인 제한
  부재탐지: False
  비고:

v14: 고시금액 이상 일반물품 중소기업 제한
  부재탐지: False
  비고:

v15: 1억 이상- 고시금액미만 소기업 제한
  부재탐지: False
  비고: 판로지원 예외 명시한 경우, 제한 없어도 가능

v16: 1억 이상- 고시금액미만 중소기업 제한 없음
  부재탐지: True
  비고: 판로지원 예외 명시한 경우, 제한 없어도 가능

v17: 1억원 미만 일반물품 중소기업 제한
  부재탐지: False
  비고: 판로지원 예외 명시한 경우, 제한 없어도 가능

v18: 1억원 미만 일반물품 소기업 제한 없음
  부재탐지: True
  비고: 판로지원 예외 명시한 경우, 제한 없어도 가능

v19: 물품공급 확약서 입찰 시 제출
  부재탐지: False
  비고: 입찰 전 발급, 계약시 제출 등 표현 다양

v20: 입찰참가자격 (SW)
  부재탐지: True
  비고: 사업금액 기준 참여제한 다름 (20억 미만, 40억 미만, 80억 미만, 80억 이상)

v21: 공동 5% (10%)
  부재탐지: False
  비고:

v22: 현장설명회 참석업체 (자격으로 제한 여부) * 계약방법 협상만 적용
  부재탐지: False
  비고:

v23: 현장설명회 (공고기간) * 계약방법 협상 + 계약법 지방만 적용
  부재탐지: False
  비고:

v24: 공고서와 나라장터 입력값 상이
  부재탐지: False
  비고: 예산, 계약방법, 지역제한, 업종

In [16]:
#   법령 조문까지 모두 보고 싶으면:

for code, info in item_table["항목"].items():
    print(f"\n[{code}] {info['항목명']}")
    print("국가계약법:", info["국가계약법"])
    print("지방계약법:", info["지방계약법"])
    print("비고:", info["비고"])

[v1] 참가자격 특정기관 제한
국가계약법: 국가계약법 시행령 제12조 국가계약법 시행령 제21조
지방계약법: 지방계약법 시행령 제13조 지방계약법 시행령 제20조
비고:

[v2] 고시금액 미만 실적제한
국가계약법: 국가계약법 시행령 제21조 제1항 국가계약법 시행규칙 제25조
지방계약법: 지방계약법 시행령 제20조 제1항 지방계약 법시행규칙제25조 제2항 지방자치단체 입찰 및 계약 집행기준 제1장 입찰 및 계약 일반기준 제1절 총칙 7. 계약담당자 주의사항
비고: 지방 + 소액수의 가능

[v3] 실적제한 1배수 이상
국가계약법: 국가계약법 시행령 제21조 제1항 국가계약법 시행규칙 제25조 (계약예규) 정부 입찰·계약 집행기준 제2장 제한경쟁입찰의 운용 제5조
지방계약법: 지방계약법 시행령 제20조 제1항 지방계약법 시행규칙 제25조
비고: 사업예산 기준

[v4] 고시금액 이상 특정기관, 특정실적
국가계약법: (계약예규) 정부입찰계약집행기준 제2장 제한경쟁입찰의 운용 제5조
지방계약법: (행안부예규) 지방자치단체 입찰 및 계약 집행기준 제1장 입찰 및 계약 일반기준
비고: 특정기관 표현 다양

[v5] 고시금액 이상 지역제한
국가계약법: 국가계약법 시행령 제21조 국가를 당사자로하는 계약에 관한 법률 등의 재정경제부장관이 정하는 고시금액
지방계약법: 지방계약법 시행령 제20조 지방계약법 시행규칙 제24조
비고: 지방, 지자체에 따라 고시금액 다름

[v6] 고시금액 미만 지역제한 시,군,구
국가계약법: 국가계약법 시행규칙 제25조
지방계약법: 지방계약법 시행규칙 제25조 지방자치단체 입찰 및 계약집행기준 제5장 수의계약 운영요령 제3절 수의계약 대상과 운영요령 1. 금액기준에 따른 2인 이상 견적서 제출 수의계약 나. 수의계약 요령
비고: 지방 + 소액수의 가능

[v7] 고시금액 미만 지역제한 인접 확대
국가계약법: 국가계약법 시행규칙 제25조
지방계약법: 지방계약법 시행규칙 제25조 지방자치단체 입찰 및 계약집행기준 제5장 수의계약 운영요령 제3절 수의계약 대상과 운영요령 1. 금액기준에 따른 2인 이상 견적서 제출 수의계약 나. 수의계약 요령
비고: 지방 + 소액수의 가능

[v8] 중복제한 (실적+지역)
국가계약법: 국가계약법 시행규칙 제25조
지방계약법: 지방계약법 시행규칙 제25조 지방자치단체 입찰 및 계약집행기준 제5장 수의계약 운영요령 제3절 수의계약 대상과 운영요령 1. 금액기준에 따른 2인 이상 견적서 제출 수의계약 나. 수의계약 요령
비고: 지방 + 소액수의 가능

[v9] 과업지시서 특정 모델명 명시
국가계약법: (계약예규) 정부 입찰·계약 집행기준 제2장 제한경쟁입찰의 운용 제5조
지방계약법: (행안부예규) 지방자치단체 입찰 및 계약 집행기준 제1장 입찰 및 계약일반기준 7. 계약담당자 주의사항
비고:

[v10] 중기간 경쟁제품 입찰 직생 없음
국가계약법: 중소기업제품 구매촉진 및 판로지원에 관한 법률 제9조 중소기업자간 경쟁제품 및 공사용자재 직접구매 대상 품목 지정 내역
지방계약법: 중소기업제품 구매촉진 및 판로지원에 관한 법률 제9조 중소기업자간 경쟁제품 및 공사용자재 직접구매 대상 품목 지정 내역
비고:

[v11] 중기간 경쟁제품 입찰 중소 없음
국가계약법: 국가계약법 시행령 제21조 중소기업제품 구매촉진 및 판로지원에 관한 법률 제7조 제1항 중소기업자간 경쟁제품 및 공사용자재 직접구매 대상 품목 지정 내역
지방계약법: 지방계약법 시행령 제20조 중소기업제품 구매촉진 및 판로지원에 관한 법률 제7조 제1항 중소기업자간 경쟁제품 및 공사용자재 직접구매 대상 품목 지정 내역
비고:

[v12] 일반제품 직생 제한
국가계약법: 국가계약법 시행령 제21조
지방계약법: 지방계약법 시행령 제20조
비고: 중기간경쟁제품 고시 참고

[v13] 중기간 경쟁제품 소기업, 소상공인 제한
국가계약법: 국가계약법 시행령 제21조 중소기업제품 구매촉진 및 판로지원에 관한 법률 제7조 제1항
지방계약법: 지방계약법 시행령 제20조 중소기업제품 구매촉진 및 판로지원에 관한 법률 제7조 제1항
비고:

[v14] 고시금액 이상 일반물품 중소기업 제한
국가계약법: 국가계약법 시행령 제21조 중소기업제품 구매촉진 및 판로지원에 관한 법률 시행령 제2조의2 제1항,제2조의3
지방계약법: 지방계약법 시행령 제20조 중소기업제품 구매촉진 및 판로지원에 관한 법률 시행령 제2조의2 제1항,제2조의3
비고:

[v15] 1억 이상- 고시금액미만 소기업 제한
국가계약법: 국가계약법 시행령 제21조 중소기업제품 구매촉진 및 판로지원에 관한 법률 시행령 제2조의2 제1항,제2조의3
지방계약법: 지방계약법 시행령 제20조 중소기업제품 구매촉진 및 판로지원에 관한 법률 시행령 제2조의2 제1항,제2조의3
비고: 판로지원 예외 명시한 경우, 제한 없어도 가능

[v16] 1억 이상- 고시금액미만 중소기업 제한 없음
국가계약법: 국가계약법 시행령 제21조 중소기업제품 구매촉진 및 판로지원에 관한 법률 시행령 제2조의2 제1항,제2조의3
지방계약법: 지방계약법 시행령 제20조 중소기업제품 구매촉진 및 판로지원에 관한 법률 시행령 제2조의2 제1항,제2조의3
비고: 판로지원 예외 명시한 경우, 제한 없어도 가능

[v17] 1억원 미만 일반물품 중소기업 제한
국가계약법: 국가계약법 시행령 제21조 중소기업제품 구매촉진 및 판로지원에 관한 법률 시행령 제2조의2 제1항,제2조의3
지방계약법: 지방계약법 시행령 제20조 중소기업제품 구매촉진 및 판로지원에 관한 법률 시행령 제2조의2 제1항,제2조의3
비고: 판로지원 예외 명시한 경우, 제한 없어도 가능

[v18] 1억원 미만 일반물품 소기업 제한 없음
국가계약법: 국가계약법 시행령 제21조 중소기업제품 구매촉진 및 판로지원에 관한 법률 시행령 제2조의2 제1항,제2조의3
지방계약법: 지방계약법 시행령 제20조 중소기업제품 구매촉진 및 판로지원에 관한 법률 시행령 제2조의2 제1항,제2조의3
비고: 판로지원 예외 명시한 경우, 제한 없어도 가능

[v19] 물품공급 확약서 입찰 시 제출
국가계약법: 국가계약법 시행령 제12조 국가계약법 시행규칙 제17조 (계약예규)정부 입찰·계약 집행기준 제2장 제한경쟁입찰의 운용 제5조의3
지방계약법: 지방계약법 시행령 제13조 지방계약법시행규칙제17조 (행안부예규) 지방자치단체 입찰 및 계약 집행기준 제1장 입찰 및 계약일반기준 7. 계약담당자 주의사항
비고: 입찰 전 발급, 계약시 제출 등 표현 다양

[v20] 입찰참가자격 (SW)
국가계약법: 소프트웨어진흥법 중소 소프트웨어사업자의 사업 참여 지원에 관한 지침 제2조 별표1
지방계약법: 소프트웨어진흥법 중소 소프트웨어사업자의 사업 참여 지원에 관한 지침 제2조 별표1
비고: 사업금액 기준 참여제한 다름 (20억 미만, 40억 미만, 80억 미만, 80억 이상)

[v21] 공동 5% (10%)
국가계약법: (계약예규) 공동계약운용요령
지방계약법: (행안부예규) 지방자치단체 입찰 및 계약 집행기준 제6장 공동계약 운영요령
비고:

[v22] 현장설명회 참석업체 (자격으로 제한 여부) * 계약방법 협상만 적용
국가계약법: 국가계약법 시행령 제43조 6항 삭제(‘19.12.18 시행)
지방계약법: 지방계약법 시행령 제43조 7항 삭제 (’22. 9. 20. 시행령 개정으로 삭제)
비고:

[v23] 현장설명회 (공고기간) * 계약방법 협상 + 계약법 지방만 적용
국가계약법: 해당 없음(위반 성립 불가) — 항목명 주석대로 계약방법 협상 + 지방계약 건에만 적용.
지방계약법: 지방계약법시행령 제35조 (행안부예규) 지방자치단체 입찰시 낙찰자 결정기준 제7장 협상에 의한 계약 낙찰자 결정기준 제3절 입찰과 계약상대자 결정절차
비고:

[v24] 공고서와 나라장터 입력값 상이
국가계약법: 해당 없음 — 조문 없는 대조형 항목(나라장터 입력값과 공고서 내용의 일치 여부 점검).
지방계약법: 해당 없음 — 조문 없는 대조형 항목(나라장터 입력값과 공고서 내용의 일치 여부 점검).
비고: 예산, 계약방법, 지역제한, 업종