### 1. 임베딩
- 텍스트를 문장 단위로 벡터 : [0.25, 0.12, 0.11]으로 변환 예시로 들 수 있다
- 검색, 추천시스템, RAG(챗봇) -> 벡터 변환형식

### 2. 임베딩 모델 준비 
- 한국어에 강한 최신 모델 : 경량화된 모델 사용 -> cpu 사용 가능

In [1]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("dragonkue/multilingual-e5-small-ko-v2")
print("모델 준비 완료")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\study-with-ai\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Lee\.cache\huggingface\hub\models--dragonkue--multilingual-e5-small-ko-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/217 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/23.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/628 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  471MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/965 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

모델 준비 완료

### E5 - 모델 사용법 익히기 - 
- query : 질문 입력할 때
- passage : 검색 대상이 되는 문서

In [3]:
sentence = "오늘 점심 메뉴는?"
with_prefix=model.encode("query:" + sentence, normalize_embeddings=True) # 2번재 파라미터 유사도 계산 
without_prefix=model.encode(sentence, normalize_embeddings=True) # 2번재 파라미터 유사도 계산 

print("접두사가 있을 때", with_prefix[:10])
print("접두사가 있을 때", without_prefix[:10])

접두사가 있을 때 [ 0.03057274 -0.00737129 -0.09526572  0.01687642  0.07531504 -0.04751493
  0.03268289  0.01705527  0.04623772  0.063585  ]
접두사가 있을 때 [ 0.02251527 -0.00308811 -0.0859407   0.00292922  0.088636   -0.04761829
  0.04911163  0.01086638  0.05150406  0.07169256]

In [ ]:
# sentence = ["오늘 점심으로 무엇을 먹을까요?",
#             "오늘 점심은 일식인가요?",
#             "오늘 점심은 중식인가요?",
#             "오늘 점심은 저녁에 어떤 메뉴를 먹을 지 고민해봐요",
#             "저녁에 뭐해요?",
#             "주식은 언제 떡상 할까요?"]

sentence = ["오늘 점심으로 무엇을 먹을까요?",
             "오늘 점심은 일식인가요?",
             "오늘 점심은 중식인가요?",
             "오늘 점심은 저녁에 어떤 메뉴를 먹을 지 고민해봐요",
             "저녁에 뭐해요?",
             "주식은 언제 떡상 할까요?"]

vecs = model.encode(sentence, normalize_embeddings=True)

In [8]:
vecs.shape

(6, 384)

In [39]:
# 기사 내용을 통째로 벡터로 바꾸면
import pandas as pd

df = pd.read_csv("../data/11-1_뉴스정제.csv") 
df['정제본문'][0]

'서울 연합뉴스 현대백화점그룹이 광주광역시에 서울 여의도 더현대 서울 과 같은 문화복합몰을 만든다고 6일 밝혔다'

In [38]:
df['passage_add'] = df['정제본문'].apply(lambda x: "passage"+ x)
df.head(1)

,제목,본문,카테고리,요약,출처URL,정제본문,passage_add
0,현대백화점그룹 더현대 광주 추진,서울 연합뉴스 현대백화점그룹이 광주광역시에 서울 여의도 더현대 서울 과 같은 문화복...,경제,"6 6일 현대백화점그룹이 광주시에 문화복합몰을 만든다고 6일 밝혔으며, 광주시는 서...",https://n.news.naver.com/mnews/article/001/001...,서울 연합뉴스 현대백화점그룹이 광주광역시에 서울 여의도 더현대 서울 과 같은 문화복...,passage서울 연합뉴스 현대백화점그룹이 광주광역시에 서울 여의도 더현대 서울 과...

In [41]:
article_vec=model.encode(df['정제본문'].tolist()[:100], normalize_embeddings=True)
print(article_vec)

[[ 0.04744077  0.04341251 -0.04399779 ...  0.06326543 -0.08641391
   0.01726929]
 [ 0.03891128  0.04919324 -0.08968784 ...  0.01063687 -0.07118414
   0.0072831 ]
 [ 0.0992108  -0.0204195   0.01587223 ...  0.08357667 -0.03688203
  -0.04291758]
 ...
 [ 0.01680643  0.01068763 -0.03125948 ...  0.01977171  0.02480885
   0.0051817 ]
 [ 0.04114025  0.01449313 -0.08008035 ...  0.02991807 -0.01783201
   0.03646773]
 [ 0.06273349 -0.05472916 -0.03805257 ...  0.03129239 -0.0331208
   0.00247542]]

In [44]:
from sentence_transformers import util

query = "경제 상황이 어떻게 되고 있어?"

def search_text(query, k=3):    # 질문과 유사한 문서 최대 k 개 가져오기
    query_vec = model.encode("query: " + query, normalize_embeddings=True)
    similarity = util.cos_sim(query_vec, article_vec)[0]
    for i in similarity.argsort(descending=True)[:k]:
        i = int(i)
        print(f"{similarity[i]}, {df['정제본문'].iloc[i]}")

In [45]:
search_text(query)

0.5671266317367554, 경제와이드 모닝벨 조간 브리핑 장연재 조간브리핑입니다 발길 끊는 개미들 거래대금 20개월만에 최저 동학개미들이 국내 주식시장을 떠나고 있다는 기사 먼저 보겠습니다 중앙일보입니다 미국발 금리 인상과 세계 경제 침체 우려로 올해에만 코스피가 20 넘게 급락하자 개인투자자들이 증시를 이탈하고 있습니다 코스피에서 개인 투자자의 하루 평균 거래 대금은 4조 3 009억 원으로 2년 4개월 만에 최저 수준을 기록했습니다 증시 대기자금인 투자자예탁금은 지난달 말 기준 반년 만에 10조 원이 줄었고 빚을 내 투자한 후 아직 갚지 않은 금액인 신용거래융자 잔고도 같은 기간 5조 원 이상 줄었습니다 이런 가운데 당분간 전 세계의 경기 침체 공포로 국내증시 반등을 기대하긴 어렵다는 의견이 지배적인데요 반면 일부 증권가에서는 기존 악재가 반영된 만큼 약세장을 오히려 기회로 삼아야 한다는 의견도 있습니다 지방 중심 역전세 깡통아파트 확산 경향신문 기사입니다 최근 지방의 저가 아파트를 중심으로 전세가격이 매매가격보다 높은 역전세 현상이 나타나고 있습니다 정부의 다주택자 규제 완화 조치 이후 매물이 쌓이고 있지만 금리가 오르자 집을 사려는 사람이 없어 집값은 하락하고 있습니다 반면 전세시장은 신규 계약체결 시점에 경신까지 염두에 두고 4년 치 상승분을 미리 가격에 반영하려는 경향이 있어서 역전세가 발생하고 있는 건데요 전세계약 시점에 집값이 이미 전세가격보다 낮다면 보증금을 보호받을 수 없어서 문제가 되고 있습니다 이런 현상은 현재까지 갭투자가 주로 이뤄지는 3억 원 이하 지방 저가 아파트에서 주로 나타나는데요 전문가들은 서울 집값은 큰 변화가 없기 때문에 전국적인 문제로 보기는 어렵다고 분석했습니다 경기 침체에 빅테크 감원 시작됐다 전 세계 기업에 감원 공포가 불고 있다는 조선일보 기사도 보겠습니다 코로나 팬데믹 기간 큰돈을 벌며 조직 규모를 키웠던 테크 기업들 너도나도 긴축 경영에 돌입하고 있습니다 인플레이션과 금리 인상 등으로 사업 환경이 급속도로 악화되고 있기 때문입니다 페이스북은 올해 신규 채용을 당초 계획보다 30 줄이기로 했고 테슬라는 정규직의 10 인 6 000여 명에 대해 해고를 예고했습니다 중국 빅테크 기업인 텐센트도 올 상반기 전체 인력의 10 15 인력을 감축했습니다 국내 대기업들도 타격이 불가피해 보이는데요 네이버는 올해 신규 채용을 작년보다 30 정도 줄인다는 계획입니다 수주 늘어도 속타는 조선업 설계인력 6년새 70 급감 매일경제 신문 기사입니다 13년여 만에 최대 수주 실적을 이어가고 있는 한국 조선 산업이 이중의 인력 부족 현상을 겪고 있습니다 당장 올해 하반기 늘어나는 건조 물량을 소화해낼 생산 인력이 부족하고 미래 성장 동력을 이끌 설계 연구개발 부문 인력도 과거의 절반 이하로 최저 수준을 유지하고 있습니다 장기간 지속된 불황으로 조선업계는 다른 산업 현장에 비해 처우가 낮고 불황 호황에 따른 온도 차가 커 고용 안정성이 낮은 탓입니다 결국 장기간 지속된 보릿고개 여파가 국내 조선 산업의 현재 미래 모두 발목을 잡고 있다는 우려가 커지고 있습니다 벌써 37 8도 찜통 장맛비 내릴 때까지 더위 견뎌야 한겨레 기사입니다 어제 3일 참 많이 더웠죠 서울 낮 최고 기온이 올여름 들어 가장 높은 34 2도를 기록했고 경기 시흥시 신형동에서 37 8도가 측정되는 등 전국이 폭염으로 몸살을 앓았습니다 폭염은 모레인 6일까지 이어질 것으로 보입니다 제4호 태풍 에어리 가 한반도를 비껴갔지만 고온다습한 공기가 유입되면서 강한 햇볕과 높은 습도에 의해 체감온도가 크게 오르고 있기 때문인데요 오늘 전국 대부분 지역에 폭염특보가 발효된 가운데 최고 체감온도가 35도 안팎까지 오르고 밤사이 열대야가 나타나는 곳이 있겠습니다 이번 더위는 물러났던 장맛비가 7일께 다시 찾아오면 한풀 꺾일 것으로 보입니다
0.542269766330719, 유럽중앙은행 본부 건물 AFP 뉴스1 서울 뉴스1 박형기 기자 금리인상으로 인한 세계 경기 침체 우려가 지속되면서 유럽증시도 일제히 하락 출발하고 있다 1일 오후 4시20분 현재 한국시간 기준 독일의 닥스는 1 17 영국의 FTSE는 0 79 프랑스의 까그는 0 77 각각 하락하고 있다 범유럽지수인 스톡스600은 0 98 하락하고 있다 전일에도 유럽증시는 일제히 급락했었다 독일의 닥스가 1 69 영국의 FTSE가 1 96 프랑스의 까그지수가 1 80 각각 급락했다 범유럽지수인 스톡스600지수는 1 50 하락했다 이는 인플레이션 고조로 각국 중앙은행이 공격적인 금리인상에 나섬에 따라 글로벌 경기가 침체할 것이란 우려가 지속되고 있기 때문으로 풀이된다 앞서 마감한 아시아 증시도 같은 이유로 일제히 하락 마감했다 일본 닛케이가 1 73 한국 코스피가 1 17 호주 ASX지수가 0 43 중국 상하이종합지수가 0 32 각각 하락했다
0.541828453540802, 한은 우크라 사태 국내 물가 영향 원자재 해외 의존도 높은 산업 타격 러시아의 우크라이나 침공 중국 봉쇄 조치 등 최근 글로벌 공급망 차질이 기업의 비용 부담으로 이어져 이미 천정부지로 치솟는 물가 오름세가 더 커질 수 있다는 경고가 나왔다 공급망 차질이 지속되면 자동차와 2차전지 등 일부 업종은 생산에도 영향을 받을 것으로 보인다 한국은행은 4일 발표한 최근 글로벌 공급망 차질의 특징 및 국내 산업에 미치는 영향 보고서에서 우크라이나 사태 장기화 글로벌 식량 수급 불안 중국의 제로 코로나 정책 유지 등으로 향후 글로벌 공급망의 불확실성이 크다 며 이런 리스크가 현실화하면 대외 의존도가 높은 우리나라는 물가 오름세가 심화하고 생산에 대한 영향도 확대될 가능성이 있다 고 진단했다 보고서에 따르면 글로벌 공급망 차질로 인해 자동차 건설 기계장비 등 일부 산업은 부품 자재 수급 차질이 빚어져 생산이 일부 제약됐다 직접적인 생산 차질은 다른 국가들과 비교해 상대적으로 큰 편은 아니라는 게 한은의 설명이다 아울러 원자재 중간재 가격이 상승하면서 대부분 산업에서 비용 부담은 커졌다 실제로 생산단계별 물가를 보면 5월 기준으로 원재료는 1년 전보다 60 8 상승했고 중간재는 15 4 나 뛰었다 생산자물가 통계에서 공산품으로 분류된 품목 중 가격 상승률이 5 이상인 품목의 비중은 절반을 넘었고 가격 상승률이 10 이상인 품목은 약 40 에 달한다 생산자들이 제품을 만드는 데 드는 비용이 늘어난 만큼 앞으로 소비자물가에도 영향을 미칠 전망이다 MobileAdNew center 한은은 우크라이나 사태 등 공급망 차질이 길어지면 원자재 해외 의존도가 높은 우리 산업에 부정적인 영향을 미칠 것으로 봤다 보고서는 자동차 2차전지 등에 사용되는 주요 필수 소재인 마그네슘 희토류 리튬 등의 대중 의존도는 80 이상이며 크립톤 제논 팔라듐 등의 대러시아 우크라이나 의존도는 30 이상 이라며 글로벌 공급망 상황과 국내 산업의 취약성을 면밀히 점검하고 향후 글로벌 공급망의 재편에도 적극 대응해 나갈 필요가 있다 고 밝혔다

In [46]:
query = "오늘 점심메뉴 뭐야?"
query = "요새 경제도 않좋은데 가격까지 고려한 오늘 점심 메뉴가 뭐야?"
search_text(query)

0.5128874182701111, 유류세 인하 폭이 37 로 확대 적용된 1일 오후 서울 서초구 서울만남의광장 휴게소 주유소에 주유를 위해 대기중인 차량이 줄지어 서 있다 유류세 인하로 이 주유소에서는 휘발유가 리터당 2068원 경유가 2152원으로 판매되고 있다 이날 오전 9시 기준 전국 평균 휘발유 가격은 전날보다 11 37원 내린 리터당 2133 53원을 나타냈다 전국 평균 경유 가격도 전날보다 7 38원 내린 2160 28원을 기록했다 사진영상기획부 발로 뛰는 더팩트는 24시간 여러분의 제보를 기다립니다
0.49696770310401917, 경제와이드 모닝벨 조간 브리핑 장연재 조간브리핑입니다 발길 끊는 개미들 거래대금 20개월만에 최저 동학개미들이 국내 주식시장을 떠나고 있다는 기사 먼저 보겠습니다 중앙일보입니다 미국발 금리 인상과 세계 경제 침체 우려로 올해에만 코스피가 20 넘게 급락하자 개인투자자들이 증시를 이탈하고 있습니다 코스피에서 개인 투자자의 하루 평균 거래 대금은 4조 3 009억 원으로 2년 4개월 만에 최저 수준을 기록했습니다 증시 대기자금인 투자자예탁금은 지난달 말 기준 반년 만에 10조 원이 줄었고 빚을 내 투자한 후 아직 갚지 않은 금액인 신용거래융자 잔고도 같은 기간 5조 원 이상 줄었습니다 이런 가운데 당분간 전 세계의 경기 침체 공포로 국내증시 반등을 기대하긴 어렵다는 의견이 지배적인데요 반면 일부 증권가에서는 기존 악재가 반영된 만큼 약세장을 오히려 기회로 삼아야 한다는 의견도 있습니다 지방 중심 역전세 깡통아파트 확산 경향신문 기사입니다 최근 지방의 저가 아파트를 중심으로 전세가격이 매매가격보다 높은 역전세 현상이 나타나고 있습니다 정부의 다주택자 규제 완화 조치 이후 매물이 쌓이고 있지만 금리가 오르자 집을 사려는 사람이 없어 집값은 하락하고 있습니다 반면 전세시장은 신규 계약체결 시점에 경신까지 염두에 두고 4년 치 상승분을 미리 가격에 반영하려는 경향이 있어서 역전세가 발생하고 있는 건데요 전세계약 시점에 집값이 이미 전세가격보다 낮다면 보증금을 보호받을 수 없어서 문제가 되고 있습니다 이런 현상은 현재까지 갭투자가 주로 이뤄지는 3억 원 이하 지방 저가 아파트에서 주로 나타나는데요 전문가들은 서울 집값은 큰 변화가 없기 때문에 전국적인 문제로 보기는 어렵다고 분석했습니다 경기 침체에 빅테크 감원 시작됐다 전 세계 기업에 감원 공포가 불고 있다는 조선일보 기사도 보겠습니다 코로나 팬데믹 기간 큰돈을 벌며 조직 규모를 키웠던 테크 기업들 너도나도 긴축 경영에 돌입하고 있습니다 인플레이션과 금리 인상 등으로 사업 환경이 급속도로 악화되고 있기 때문입니다 페이스북은 올해 신규 채용을 당초 계획보다 30 줄이기로 했고 테슬라는 정규직의 10 인 6 000여 명에 대해 해고를 예고했습니다 중국 빅테크 기업인 텐센트도 올 상반기 전체 인력의 10 15 인력을 감축했습니다 국내 대기업들도 타격이 불가피해 보이는데요 네이버는 올해 신규 채용을 작년보다 30 정도 줄인다는 계획입니다 수주 늘어도 속타는 조선업 설계인력 6년새 70 급감 매일경제 신문 기사입니다 13년여 만에 최대 수주 실적을 이어가고 있는 한국 조선 산업이 이중의 인력 부족 현상을 겪고 있습니다 당장 올해 하반기 늘어나는 건조 물량을 소화해낼 생산 인력이 부족하고 미래 성장 동력을 이끌 설계 연구개발 부문 인력도 과거의 절반 이하로 최저 수준을 유지하고 있습니다 장기간 지속된 불황으로 조선업계는 다른 산업 현장에 비해 처우가 낮고 불황 호황에 따른 온도 차가 커 고용 안정성이 낮은 탓입니다 결국 장기간 지속된 보릿고개 여파가 국내 조선 산업의 현재 미래 모두 발목을 잡고 있다는 우려가 커지고 있습니다 벌써 37 8도 찜통 장맛비 내릴 때까지 더위 견뎌야 한겨레 기사입니다 어제 3일 참 많이 더웠죠 서울 낮 최고 기온이 올여름 들어 가장 높은 34 2도를 기록했고 경기 시흥시 신형동에서 37 8도가 측정되는 등 전국이 폭염으로 몸살을 앓았습니다 폭염은 모레인 6일까지 이어질 것으로 보입니다 제4호 태풍 에어리 가 한반도를 비껴갔지만 고온다습한 공기가 유입되면서 강한 햇볕과 높은 습도에 의해 체감온도가 크게 오르고 있기 때문인데요 오늘 전국 대부분 지역에 폭염특보가 발효된 가운데 최고 체감온도가 35도 안팎까지 오르고 밤사이 열대야가 나타나는 곳이 있겠습니다 이번 더위는 물러났던 장맛비가 7일께 다시 찾아오면 한풀 꺾일 것으로 보입니다
0.4901835322380066, 중기부 주관 제1회 여성기업주간 인식 제고 및 홍보 디지털데일리 이안나 기자 공영홈쇼핑이 여성기업 판로 확대를 위해 힘쓴다 공영홈쇼핑은 올해 신설된 제1회 여성기업 주간 을 맞아 오는 5일부터 8일까지 TV홈쇼핑과 공영라방을 통해 여성기업 판로지원에 나선다고 1일 밝혔다 공영홈쇼핑에 따르면 여성기업주간 은 여성 경제인 자긍심 고취 및 경제 활동 촉진을 위해 마련됐다 지난해 개정된 여성기업지원에 관한 법률 에 따라 새롭게 신설된 주간이다 중소벤처기업부는 올해부터 매년 7월 첫째 주를 여성기업 주간 으로 정하고 다양한 행사를 펼친다 공영홈쇼핑은 이번 여성기업주간 중 TV홈쇼핑을 통해 8시간 특별 생방송을 편성해 판로지원에 나선다 대표적인 상품은 콩세상 된장찌개 해장국 담은제주보리 성신옥찰떡 트레비코끼리비데 국내산 한가람연잎밥 항아골청국장 메이듀스타 스니커즈 태광크리스피롤 등 총 8개다 이중 국내산 한가람 연잎밥 은 모바일 라이브 커머스 공영라방 과 동시에 방송한다 8일 오전 11시 공영라방에선 공영홈쇼핑 대표적 여성기업 판로지원 사례로 손꼽히는 조금자 대표가 출연해 여성기업 성공담을 소개한다 조금자 채소잡곡 으로 잘 알려진 조 대표는 귀농 후 수 차례 좌절을 겪다 공영홈쇼핑을 만나 성공한 주부 최고경영자 CEO 로 불린다 공영홈쇼핑 관계자는 앞으로도 여성기업을 비롯해 청년기업 벤처 창업기업 소상공인 등 다양한 분야 기업들에 힘이 되는 든든한 판로가 되겠다 고 말했다

In [49]:
query = "대한민국 악재 영향 찾아줘"
search_text(query,5)

0.5788738131523132, 한은 우크라 사태 국내 물가 영향 원자재 해외 의존도 높은 산업 타격 러시아의 우크라이나 침공 중국 봉쇄 조치 등 최근 글로벌 공급망 차질이 기업의 비용 부담으로 이어져 이미 천정부지로 치솟는 물가 오름세가 더 커질 수 있다는 경고가 나왔다 공급망 차질이 지속되면 자동차와 2차전지 등 일부 업종은 생산에도 영향을 받을 것으로 보인다 한국은행은 4일 발표한 최근 글로벌 공급망 차질의 특징 및 국내 산업에 미치는 영향 보고서에서 우크라이나 사태 장기화 글로벌 식량 수급 불안 중국의 제로 코로나 정책 유지 등으로 향후 글로벌 공급망의 불확실성이 크다 며 이런 리스크가 현실화하면 대외 의존도가 높은 우리나라는 물가 오름세가 심화하고 생산에 대한 영향도 확대될 가능성이 있다 고 진단했다 보고서에 따르면 글로벌 공급망 차질로 인해 자동차 건설 기계장비 등 일부 산업은 부품 자재 수급 차질이 빚어져 생산이 일부 제약됐다 직접적인 생산 차질은 다른 국가들과 비교해 상대적으로 큰 편은 아니라는 게 한은의 설명이다 아울러 원자재 중간재 가격이 상승하면서 대부분 산업에서 비용 부담은 커졌다 실제로 생산단계별 물가를 보면 5월 기준으로 원재료는 1년 전보다 60 8 상승했고 중간재는 15 4 나 뛰었다 생산자물가 통계에서 공산품으로 분류된 품목 중 가격 상승률이 5 이상인 품목의 비중은 절반을 넘었고 가격 상승률이 10 이상인 품목은 약 40 에 달한다 생산자들이 제품을 만드는 데 드는 비용이 늘어난 만큼 앞으로 소비자물가에도 영향을 미칠 전망이다 MobileAdNew center 한은은 우크라이나 사태 등 공급망 차질이 길어지면 원자재 해외 의존도가 높은 우리 산업에 부정적인 영향을 미칠 것으로 봤다 보고서는 자동차 2차전지 등에 사용되는 주요 필수 소재인 마그네슘 희토류 리튬 등의 대중 의존도는 80 이상이며 크립톤 제논 팔라듐 등의 대러시아 우크라이나 의존도는 30 이상 이라며 글로벌 공급망 상황과 국내 산업의 취약성을 면밀히 점검하고 향후 글로벌 공급망의 재편에도 적극 대응해 나갈 필요가 있다 고 밝혔다
0.5358407497406006, 바클레이스 경상흑자 900억달러 늘어 위안화 1 8 절상 미국의 성조기와 중국의 오성홍기 AFP 뉴스1 서울 뉴스1 신기림 기자 미국이 대중 관세를 철폐해도 미국의 인플레이션과 중국 위안화에 미치는 영향력은 크지 않을 것 modest 이라고 바클레이스가 전망했다 5일 블룸버그에 따르면 바클레이스 애널리스트들은 대중 관세가 완전히 사라져도 미국의 인플레이션에 직접 미치는 효과는 최대 한 차례로 0 3 포인트 p 낮추는 데에 그칠 것이라고 예상했다 미국의 소비재 항목 바스켓 에서 중국산이 차지하는 비중이 상대적으로 작기 때문이라고 관세 철폐가 인플레이션에 미치는 영향력이 크지 않다고 바클레이스는 설명했다 대중관세 철폐가 미국 인플레이션에 끼치는 영향력은 양동이의 물 한 방울 drop in the bucket 즈음 되겠다고 바클레이스 애널리스트들은 표현했다 또 미국의 통화정책을 숙고하는 데에 미치는 영향력도 없을 것이라고 예상했다 관세를 부분적으로만 철폐하면 인플레이션 압박을 낮추는 효과는 더 작을 것이라고 바클레이스는 지적했다 미국과 중국 사이 무역 긴장이 잠재적으로 해소될 가능성에도 중국 위안화가 고속충전 supercharger 될 것 같지도 않다고 바클레이스는 지적했다 관세가 양국에서 모두 철폐되면 중국의 경상흑자는 900억달러 늘어날 것이라고 바클레이스 애널리스트들은 추산했다 이는 위안화 가치를 1 8 끌어 올리는 효과지만 관세가 단계적이고 부분적으로 철폐될 가능성이 높은 만큼 위안화 절상효과는 그 보다 작을 것이라고 바클레이스는 전망했다 또 위안화의 급격한 절상은 안정적 환율관리를 원하는 중앙은행 인민은행도 원하지 않는 바일 것이라고 바클레이스는 예상했다 블룸버그 월스트리트저널 WSJ 등 주요 경제매체에 따르면 조 바이든 미국 대통령은 이번주 일부 대중 관세를 철폐한다고 공식적으로 발표할 것으로 보인다 류허 중국 부총리와 재닛 옐런 미국 재무장관은 5일 경제 제재 관세와 관련해 화상회의를 가졌다고 양국 정부는 밝혔다
0.530942440032959, 방기선 기재차관 비상경제차관회의 주 2회 이상 전국 순회하면서 점검 방기선 기획재정부 1차관 왼쪽 이 1일 정부서울청사에서 열린 비상경제차관회의에서 모두발언을 하고 있다 사진 뉴스1 파이낸셜뉴스 정부가 유류세 추가 인하 조치 시행 첫날인 1일 전국 주유소를 대상으로 점검반을 꾸려 현장 점검에 나서기로 했다 직영 주유소를 중심으로 즉시 인하분을 반영토록 하고 가격담합 등 불법행위 여부를 확인하기 위한 목적이다 방기선 기획재정부 1차관은 이날 정부서울청사에서 열린 제2차 비상경제차관회의 모두발언을 통해 이 같이 밝혔다 방 차관은 오늘부터 유류세 인하 확대조치 시행에 따라 휘발유는 리터당 57원 경유는 리터당 38원이 인하될 예정 이라며 유류세 인하 효과가 시장 가격에 즉시 반영될 수 있도록 산업부를 중심으로 정유사 등 업계와의 협력을 강화하겠다 고 말했다 이어 정유사 직영주유소에서는 오늘 시행 즉시 가격을 인하하고 자영주유소에서도 최대한 조속히 인하된 물량이 공급될 수 있도록 비상운송계획을 통해 물량 공급에 차질이 없도록 준비하겠다 고 설명했다 관계기관 합동 점검단은 산업통상자원부 국토교통부 공정거래위원회 국세청 등을 중심으로 운영한다 방 차관은 주 2회 이상 전국 순회 주유소 현장점검을 집중실시하고 물가상승기에 편승한 지역별 주유소 가격 담합 가짜석유 유통 등과 같은 불법행위에 대해서는 엄중조치할 계획 이라며 정유사를 대상으로도 수급 품질을 집중점검해 위반행위 적발시 단호하게 대처할 것 이라고 강조했다 방 차관은 이날 산업부에서 발표한 6월 수출입 동향과 관련해 어려운 대외여건에서도 증가세를 이어가는 모습이라고 평가했다 방 차관은 무역수지 적자폭은 지난달보다 다소 확대됐지만 6월 하순 들어 수출이 빠르게 회복하면서 적자폭을 상당히 줄일 수 있었다 며 이 같은 수출 회복흐름이 하반기에도 흔들림 없이 유지 확대될 수 있도록 최선의 노력을 기울이겠다 고 했다
0.5181362628936768, 재무위험기관 14곳 중 12곳 에너지 기업 LH도 관리대상 서울 한국전력공사 서초지사 연합뉴스 자료사진 세종 연합뉴스 박용주 기자 윤석열 정부 들어 에너지 공기업들이 대거 재무위험기관에 포함되면서 그 배경에 이목이 쏠리고 있다 코레일 한국철도공사 은 비 에너지 공기업 중에선 드물게 재무위험기관에 이름을 올렸다 4일 기획재정부에 따르면 최근 정부가 선정한 재무위험기관 14곳 중 12곳이 에너지 공기업이다 한국전력공사와 한국수력원자력 발전5사 등 한전 자회사 지역난방공사가 사업 수익성 악화 징후 기관에 이름을 올렸다 석유공사와 광해광업공단 가스공사 석탄공사 등 자원 공기업은 재무구조 취약기관에 포함됐다 이들 에너지 공기업 12곳을 빼고 나면 한국토지주택공사 LH 가 수익성 악화 기관에 코레일이 재무구조 취약기관에 이름을 올렸을 뿐이다 재무위험기관은 재무지표와 재무성과 재무개선도 등 평가에서 낙제점을 받거나 부채비율이 200 이상인 이른바 투자 부적격 기관이다 이들 기관은 수익성을 높이고 지출을 효율화할 방안을 제시해야 한다 자산을 매각하고 인력 조직을 재정비하는 등 뼈를 깎는 구조조정 절차를 겪어야 하는 경우도 있다 정부는 중장기 재무관리계획 작성기관 중 금융형 기관을 제외한 27개 기관을 대상으로 평가를 진행해 약 절반인 14곳을 재무위험기관으로 선정했다 평가 작업을 마치고 나니 절반 가까운 공기업들이 빠져나간 가운데 에너지 공기업 12곳은 1곳도 빠짐없이 재무위험기관으로 들어갔다 이를 두고 에너지 공기업들이 정부의 눈 밖에 난 것이 아닌지 이들을 구조조정 대상으로 정조준하는 것이 아닌지 등 여러 해석이 나온다 정부 관계자는 에너지 공기업을 딱히 목표로 삼지는 않았다 면서 재무상황평가 기준선 이하이거나 부채비율이 200 이상인 공공기관을 선별했더니 이들이 모두 그대로 남은 것 이라고 설명했다 기획재정부 제공 기획재정부 제공 한전과 한국수력원자력 5개 발전 자회사는 수익성 악화기관으로 분류됐다 한전의 경우 고유가 상황에서 에너지 믹스 변화 등으로 재무구조가 악화한 점이 문제가 됐다 지난해 연결기준으로 5조9천억원 상당의 영업적자를 낸 것도 수익성 악화기관으로 선정된 배경이 된다 LH 역시 비에너지 공기업으로선 유일하게 수익성 악화 기관에 포함됐지만 상대적으로 관리 강도가 높은 대상은 아닐 것이라는 분석이 나온다 지난해 기준 부채비율이 221 로 재무위험기관 기준을 넘어섰지만 LH는 부채에 상응하는 대응자산이 있고 지난해 LH 사태 후속조치로 이미 상당 부분 구조조정이 이뤄졌기 때문이다 정부는 수익성 악화기관보다 재무구조 취약기관을 더 우려스러운 시각으로 보고 있다 이들 기관은 장기간에 걸친 수익성 악화로 취약한 재무구조가 굳어진 기관이 많다는 평가다 정부는 이 중에서도 이미 자본잠식 단계로 들어간 석유공사와 지난해 부채비율이 378 9 를 기록한 가스공사에 특단의 조치가 필요하다고 보는 것으로 전해졌다 코레일 역시 구조조정 강도가 높을 것으로 예상하는 시각이 많다 지난해 1조1천552억원 상당의 적자를 낸 데다 부채비율 역시 287 3 까지 올라 고강도 재정 건전화 계획을 요구할 가능성이 거론된다
0.5157745480537415, 경제와이드 모닝벨 조간 브리핑 장연재 조간브리핑입니다 발길 끊는 개미들 거래대금 20개월만에 최저 동학개미들이 국내 주식시장을 떠나고 있다는 기사 먼저 보겠습니다 중앙일보입니다 미국발 금리 인상과 세계 경제 침체 우려로 올해에만 코스피가 20 넘게 급락하자 개인투자자들이 증시를 이탈하고 있습니다 코스피에서 개인 투자자의 하루 평균 거래 대금은 4조 3 009억 원으로 2년 4개월 만에 최저 수준을 기록했습니다 증시 대기자금인 투자자예탁금은 지난달 말 기준 반년 만에 10조 원이 줄었고 빚을 내 투자한 후 아직 갚지 않은 금액인 신용거래융자 잔고도 같은 기간 5조 원 이상 줄었습니다 이런 가운데 당분간 전 세계의 경기 침체 공포로 국내증시 반등을 기대하긴 어렵다는 의견이 지배적인데요 반면 일부 증권가에서는 기존 악재가 반영된 만큼 약세장을 오히려 기회로 삼아야 한다는 의견도 있습니다 지방 중심 역전세 깡통아파트 확산 경향신문 기사입니다 최근 지방의 저가 아파트를 중심으로 전세가격이 매매가격보다 높은 역전세 현상이 나타나고 있습니다 정부의 다주택자 규제 완화 조치 이후 매물이 쌓이고 있지만 금리가 오르자 집을 사려는 사람이 없어 집값은 하락하고 있습니다 반면 전세시장은 신규 계약체결 시점에 경신까지 염두에 두고 4년 치 상승분을 미리 가격에 반영하려는 경향이 있어서 역전세가 발생하고 있는 건데요 전세계약 시점에 집값이 이미 전세가격보다 낮다면 보증금을 보호받을 수 없어서 문제가 되고 있습니다 이런 현상은 현재까지 갭투자가 주로 이뤄지는 3억 원 이하 지방 저가 아파트에서 주로 나타나는데요 전문가들은 서울 집값은 큰 변화가 없기 때문에 전국적인 문제로 보기는 어렵다고 분석했습니다 경기 침체에 빅테크 감원 시작됐다 전 세계 기업에 감원 공포가 불고 있다는 조선일보 기사도 보겠습니다 코로나 팬데믹 기간 큰돈을 벌며 조직 규모를 키웠던 테크 기업들 너도나도 긴축 경영에 돌입하고 있습니다 인플레이션과 금리 인상 등으로 사업 환경이 급속도로 악화되고 있기 때문입니다 페이스북은 올해 신규 채용을 당초 계획보다 30 줄이기로 했고 테슬라는 정규직의 10 인 6 000여 명에 대해 해고를 예고했습니다 중국 빅테크 기업인 텐센트도 올 상반기 전체 인력의 10 15 인력을 감축했습니다 국내 대기업들도 타격이 불가피해 보이는데요 네이버는 올해 신규 채용을 작년보다 30 정도 줄인다는 계획입니다 수주 늘어도 속타는 조선업 설계인력 6년새 70 급감 매일경제 신문 기사입니다 13년여 만에 최대 수주 실적을 이어가고 있는 한국 조선 산업이 이중의 인력 부족 현상을 겪고 있습니다 당장 올해 하반기 늘어나는 건조 물량을 소화해낼 생산 인력이 부족하고 미래 성장 동력을 이끌 설계 연구개발 부문 인력도 과거의 절반 이하로 최저 수준을 유지하고 있습니다 장기간 지속된 불황으로 조선업계는 다른 산업 현장에 비해 처우가 낮고 불황 호황에 따른 온도 차가 커 고용 안정성이 낮은 탓입니다 결국 장기간 지속된 보릿고개 여파가 국내 조선 산업의 현재 미래 모두 발목을 잡고 있다는 우려가 커지고 있습니다 벌써 37 8도 찜통 장맛비 내릴 때까지 더위 견뎌야 한겨레 기사입니다 어제 3일 참 많이 더웠죠 서울 낮 최고 기온이 올여름 들어 가장 높은 34 2도를 기록했고 경기 시흥시 신형동에서 37 8도가 측정되는 등 전국이 폭염으로 몸살을 앓았습니다 폭염은 모레인 6일까지 이어질 것으로 보입니다 제4호 태풍 에어리 가 한반도를 비껴갔지만 고온다습한 공기가 유입되면서 강한 햇볕과 높은 습도에 의해 체감온도가 크게 오르고 있기 때문인데요 오늘 전국 대부분 지역에 폭염특보가 발효된 가운데 최고 체감온도가 35도 안팎까지 오르고 밤사이 열대야가 나타나는 곳이 있겠습니다 이번 더위는 물러났던 장맛비가 7일께 다시 찾아오면 한풀 꺾일 것으로 보입니다

### 실습하기
- 내가 질문하려는 주제와 연관있는 데이터 생성
    - ex) 점심 메뉴 추천이라면
            - 리스트에 점심메뉴 관련 데이터를 데이터 프레임 형태로 만들어서 벡터화 시키자
- 질문을 걸어 얼마나 잘 찾는지 확인

In [51]:
## 1. 상품 데이터 만들기

import pandas as pd

product_df = pd.DataFrame({
    "product_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "product": [
        "경량 노트북",
        "게이밍 노트북",
        "무선 이어폰",
        "노이즈 캔슬링 헤드폰",
        "기계식 키보드",
        "인체공학 마우스",
        "휴대용 보조배터리",
        "USB-C 멀티 허브"
    ],
    "category": [
        "노트북", "노트북", "오디오", "오디오",
        "주변기기", "주변기기", "모바일", "주변기기"
    ],
    "description": [
        "가볍고 배터리가 오래가는 노트북으로 문서 작성과 인터넷 검색에 적합하다.",
        "고성능 그래픽카드가 탑재되어 게임과 영상 편집에 적합하다.",
        "작고 가벼운 무선 이어폰으로 출퇴근과 운동할 때 사용하기 좋다.",
        "외부 소음을 차단해 음악 감상과 장시간 집중에 적합한 헤드폰이다.",
        "타건감이 좋고 내구성이 뛰어나 개발자와 사무직 사용자에게 적합하다.",
        "손목 부담을 줄여주는 디자인으로 장시간 컴퓨터 작업에 적합하다.",
        "휴대하기 좋은 작은 크기로 여행이나 외출 시 스마트폰 충전에 유용하다.",
        "노트북에 연결해 HDMI, USB, SD카드 등을 동시에 사용할 수 있다."
    ],
    "price": [
        800000, 1800000, 120000, 350000,
        150000, 80000, 50000, 70000
    ]
})

In [52]:
## 2. 벡터화할 텍스트 만들기

# 상품명, 카테고리, 설명을 하나의 문장으로 합칩니다.

product_df["text"] = (
    "상품명: " + product_df["product"] +
    " 카테고리: " + product_df["category"] +
    " 설명: " + product_df["description"]
)

product_df[["product", "text"]].head()

       product                                               text
0       경량 노트북  상품명: 경량 노트북 카테고리: 노트북 설명: 가볍고 배터리가 오래가는 노트북으로 ...
1      게이밍 노트북  상품명: 게이밍 노트북 카테고리: 노트북 설명: 고성능 그래픽카드가 탑재되어 게임과...
2       무선 이어폰  상품명: 무선 이어폰 카테고리: 오디오 설명: 작고 가벼운 무선 이어폰으로 출퇴근과...
3  노이즈 캔슬링 헤드폰  상품명: 노이즈 캔슬링 헤드폰 카테고리: 오디오 설명: 외부 소음을 차단해 음악 감...
4      기계식 키보드  상품명: 기계식 키보드 카테고리: 주변기기 설명: 타건감이 좋고 내구성이 뛰어나 개...

In [53]:
## 3. 상품 벡터 만들기

passages = [
    "passage: " + text
    for text in product_df["text"].tolist()
]

product_vec = model.encode(
    passages,
    normalize_embeddings=True
)

print(product_vec.shape)

(8, 384)

In [54]:
## 4. 질문으로 상품 검색하기

from sentence_transformers import util

question = "가볍고 오래 사용할 수 있으며 문서 작업에 좋은 노트북"

query_vec = model.encode(
    "query: " + question,
    normalize_embeddings=True
)

scores = util.cos_sim(query_vec, product_vec)[0]

result_df = product_df.copy()
result_df["similarity"] = scores.cpu().numpy()

result_df = result_df.sort_values(
    "similarity",
    ascending=False
)

result_df[
    ["product", "category", "description", "price", "similarity"]
].head(3)

,product,category,description,price,similarity
0,경량 노트북,노트북,가볍고 배터리가 오래가는 노트북으로 문서 작성과 인터넷 검색에 적합하다.,800000,0.765813
1,게이밍 노트북,노트북,고성능 그래픽카드가 탑재되어 게임과 영상 편집에 적합하다.,1800000,0.638839
4,기계식 키보드,주변기기,타건감이 좋고 내구성이 뛰어나 개발자와 사무직 사용자에게 적합하다.,150000,0.586016

In [55]:
## 5. 여러 질문 테스트하기

questions = [
    "게임과 영상 편집을 할 수 있는 고성능 컴퓨터",
    "출퇴근할 때 사용할 작고 가벼운 음악 기기",
    "주변 소음을 차단하고 공부할 수 있는 제품",
    "장시간 컴퓨터를 사용해도 손목이 편한 제품",
    "여행 중 스마트폰을 충전할 수 있는 제품"
]

for question in questions:
    query_vec = model.encode(
        "query: " + question,
        normalize_embeddings=True
    )

    scores = util.cos_sim(query_vec, product_vec)[0]
    top_index = scores.argmax().item()

    print("질문:", question)
    print("추천 상품:", product_df.iloc[top_index]["product"])
    print()

질문: 게임과 영상 편집을 할 수 있는 고성능 컴퓨터
추천 상품: 게이밍 노트북

질문: 출퇴근할 때 사용할 작고 가벼운 음악 기기
추천 상품: 무선 이어폰

질문: 주변 소음을 차단하고 공부할 수 있는 제품
추천 상품: 노이즈 캔슬링 헤드폰

질문: 장시간 컴퓨터를 사용해도 손목이 편한 제품
추천 상품: 인체공학 마우스

질문: 여행 중 스마트폰을 충전할 수 있는 제품
추천 상품: 휴대용 보조배터리

In [57]:
## 6. 가격 조건까지 적용하기

#   벡터 검색은 의미가 비슷한 상품을 찾고, 가격 같은 조건은 별도로 필터링하는 것이 좋습니다.

question = "제일 많이 팔리는 상품"
max_price = 1_000_000

filtered_df = product_df[
    (product_df["category"] == "노트북") &
    (product_df["price"] <= max_price)
].copy()

filtered_vec = model.encode(
    ["passage: " + text for text in filtered_df["text"]],
    normalize_embeddings=True
)

query_vec = model.encode(
    "query: " + question,
    normalize_embeddings=True
)

scores = util.cos_sim(query_vec, filtered_vec)[0]
filtered_df["similarity"] = scores.cpu().numpy()

filtered_df.sort_values(
    "similarity",
    ascending=False
)[["product", "price", "description", "similarity"]]

  product   price                               description  similarity
0  경량 노트북  800000  가볍고 배터리가 오래가는 노트북으로 문서 작성과 인터넷 검색에 적합하다.    0.443388

In [58]:
## 1. 라이브러리 불러오기
import pandas as pd
from sentence_transformers import SentenceTransformer, util

## 2. 모델 불러오기
model = SentenceTransformer(
    "intfloat/multilingual-e5-small",
    device="cpu"
)

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

c:\study-with-ai\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Lee\.cache\huggingface\hub\models--intfloat--multilingual-e5-small. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

README.md:   0%|          | 0.00/498k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/655 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  471MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/167 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

In [59]:
  ## 3. 의상 데이터 준비
clothes_df = pd.DataFrame({
      "상품명": [
          "오버핏 린넨 셔츠",
          "슬림핏 블랙 슬랙스",
          "베이직 화이트 티셔츠",
          "캐주얼 데님 재킷",
          "플리츠 롱스커트",
          "경량 패딩 점퍼"
      ],
      "카테고리": [
          "셔츠", "바지", "티셔츠",
          "재킷", "스커트", "아우터"
      ],
      "색상": [
          "아이보리", "검정", "흰색",
          "청색", "베이지", "검정"
      ],
      "소재": [
          "린넨", "폴리에스터", "면",
          "데님", "폴리에스터", "나일론"
      ],
      "스타일": [
          "캐주얼", "오피스", "베이직",
          "캐주얼", "여성스러운", "스포티"
      ],
      "계절": [
          "여름", "사계절", "사계절",
          "봄가을", "봄가을", "겨울"
      ],
      "설명": [
          "통기성이 좋고 가벼워 더운 날씨에 입기 좋은 셔츠",
          "단정한 디자인으로 출근할 때 활용하기 좋은 바지",
          "부드러운 면 소재의 기본 티셔츠",
          "청바지와 잘 어울리는 캐주얼한 데님 아우터",
          "움직임이 편하고 여성스러운 분위기를 연출하는 스커트",
          "가볍고 보온성이 좋아 겨울철 외출에 적합한 점퍼"
      ]
  })

In [60]:
## 4. 벡터화할 문장 만들기 
clothes_df["text"] = (
    "상품명: " + clothes_df["상품명"] +
    " 카테고리: " + clothes_df["카테고리"] +
    " 색상: " + clothes_df["색상"] +
    " 소재: " + clothes_df["소재"] +
    " 스타일: " + clothes_df["스타일"] +
    " 계절: " + clothes_df["계절"] +
    " 설명: " + clothes_df["설명"]
)

clothes_df[["상품명", "text"]].head(2)

          상품명                                               text
0   오버핏 린넨 셔츠  상품명: 오버핏 린넨 셔츠 카테고리: 셔츠 색상: 아이보리 소재: 린넨 스타일: 캐...
1  슬림핏 블랙 슬랙스  상품명: 슬림핏 블랙 슬랙스 카테고리: 바지 색상: 검정 소재: 폴리에스터 스타일:...

In [61]:
## 5. 상품 문장 벡터화

#   E5 모델에서는 상품이나 문서에 passage: 를 붙입니다.

passages = [
    "passage: " + text
    for text in clothes_df["text"].tolist()
]

clothes_vec = model.encode(
    passages,
    normalize_embeddings=True,
    batch_size=8,
    show_progress_bar=True
)

print(clothes_vec.shape)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

(6, 384)

In [62]:
## 6. 질문으로 의상 검색하기

#   질문에는 query: 를 붙입니다.

question = "여름에 입기 좋고 시원하면서 출근할 때도 어울리는 옷"

query_vec = model.encode(
    ["query: " + question],
    normalize_embeddings=True
)

scores = util.cos_sim(query_vec, clothes_vec)[0]

result_df = clothes_df.copy()
result_df["similarity"] = scores.cpu().numpy()

result_df = result_df.sort_values(
    "similarity",
    ascending=False
)

result_df[
    ["상품명", "카테고리", "색상", "스타일", "similarity"]
].head(3)

          상품명 카테고리    색상  스타일  similarity
1  슬림핏 블랙 슬랙스   바지    검정  오피스    0.869822
0   오버핏 린넨 셔츠   셔츠  아이보리  캐주얼    0.868785
3   캐주얼 데님 재킷   재킷    청색  캐주얼    0.846643

In [63]:
## 7. 재사용 가능한 검색 함수 만들기

def recommend_clothes(question, top_k=3):
    query_vec = model.encode(
        ["query: " + question],
        normalize_embeddings=True
    )

    scores = util.cos_sim(query_vec, clothes_vec)[0]

    result = clothes_df.copy()
    result["similarity"] = scores.cpu().numpy()

    return (
        result
        .sort_values("similarity", ascending=False)
        .head(top_k)
    )

# 사용 방법:

recommend_clothes(
    "편하게 입을 수 있고 청바지와 잘 어울리는 옷",
    top_k=3
)

,상품명,카테고리,색상,소재,스타일,계절,설명,text,similarity
3,캐주얼 데님 재킷,재킷,청색,데님,캐주얼,봄가을,청바지와 잘 어울리는 캐주얼한 데님 아우터,상품명: 캐주얼 데님 재킷 카테고리: 재킷 색상: 청색 소재: 데님 스타일: 캐주얼...,0.866738
1,슬림핏 블랙 슬랙스,바지,검정,폴리에스터,오피스,사계절,단정한 디자인으로 출근할 때 활용하기 좋은 바지,상품명: 슬림핏 블랙 슬랙스 카테고리: 바지 색상: 검정 소재: 폴리에스터 스타일:...,0.843371
0,오버핏 린넨 셔츠,셔츠,아이보리,린넨,캐주얼,여름,통기성이 좋고 가벼워 더운 날씨에 입기 좋은 셔츠,상품명: 오버핏 린넨 셔츠 카테고리: 셔츠 색상: 아이보리 소재: 린넨 스타일: 캐...,0.843364

##### 1.처음 한 번만 실행합니다.
- %pip install datasets

In [ ]:
## 2. 데이터 불러오기

from datasets import load_dataset
import pandas as pd

dataset = load_dataset(
    "alexkstern/myntra_fashion_dataset",
    split="train"
)

fashion_df = dataset.to_pandas()

fashion_df.head()

## 3. 데이터 구조 확인

fashion_df.shape
fashion_df.columns
fashion_df.info()
fashion_df.isna().sum()

# 주요 컬럼은 다음과 같습니다.

# name
# sku
# mpn
# price
# in_stock
# currency
# brand
# description
# images
# gender

# images 컬럼은 이번 실습에서 사용하지 않습니다.

# ## 4. 의류 상품만 선택하기

# 이 데이터에는 가방, 향수, 생활용품도 일부 포함되어 있으므로 의류 관련 상품만 간단히 필터링합니다.

clothing_keywords = [
    "shirt", "t-shirt", "jeans", "trouser",
    "dress", "skirt", "jacket", "kurta",
    "shorts", "suit", "top", "saree",
    "tights", "clothing", "blazer"
]

pattern = "|".join(clothing_keywords)

clothes_df = fashion_df[
    fashion_df["name"]
    .fillna("")
    .str.lower()
    .str.contains(pattern, na=False)
].copy()

clothes_df.shape

# 필터링 결과를 확인합니다.

clothes_df[
    ["name", "brand", "price", "gender"]
].head(10)

## 5. 임베딩용 텍스트 만들기

# 상품명, 브랜드, 성별, 설명을 하나의 문장으로 합칩니다.

clothes_df["text"] = (
    "상품명: " + clothes_df["name"].fillna("").astype(str) +
    " 브랜드: " + clothes_df["brand"].fillna("").astype(str) +
    " 성별: " + clothes_df["gender"].fillna("").astype(str) +
    " 설명: " + clothes_df["description"].fillna("").astype(str)
)

## 6. 모델 불러오기

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer(
    "intfloat/multilingual-e5-small",
    device="cpu"
)

<class 'pandas.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         308 non-null    str
 1   sku          308 non-null    str
 2   mpn          308 non-null    str
 3   price        308 non-null    str
 4   in_stock     308 non-null    bool
 5   currency     308 non-null    str
 6   brand        308 non-null    str
 7   description  308 non-null    str
 8   images       308 non-null    str
 9   gender       308 non-null    str
dtypes: bool(1), str(9)
memory usage: 293.1 KB

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/20 [00:00<?, ?it/s]

(156, 384)

In [79]:
## 7. 상품 벡터 생성

passages = [
"passage: " + text
for text in clothes_df["text"].tolist()
]

clothes_vec = model.encode(
passages,
normalize_embeddings=True,
batch_size=8,
show_progress_bar=True
)

print(clothes_vec.shape)

Batches:   0%|          | 0/20 [00:00<?, ?it/s]

(156, 384)

In [80]:
## 8. 질문으로 상품 검색하기

question = "여름에 입기 좋은 여성 캐주얼 셔츠"

query_vec = model.encode(
    ["query: " + question],
    normalize_embeddings=True
)

scores = util.cos_sim(query_vec, clothes_vec)[0]

result_df = clothes_df.copy()
result_df["similarity"] = scores.cpu().numpy()

result_df.sort_values(
    "similarity",
    ascending=False
)[["name", "brand", "gender", "price", "similarity"]].head(5)

## 9. 재사용 가능한 추천 함수

def recommend_clothes(question, top_k=5):
    query_vec = model.encode(
    ["query: " + question],
    normalize_embeddings=True
)

    scores = util.cos_sim(query_vec, clothes_vec)[0]

    result = clothes_df.copy()
    result["similarity"] = scores.cpu().numpy()

    return(
        result
        .sort_values("similarity", ascending=False)
        .head(top_k)
        )

In [86]:
from IPython.display import display, HTML

result = recommend_clothes(
    "가을에 입기 좋은 남성 화려한 패션",
    top_k=5
).copy()

# 여러 이미지 URL 중 첫 번째 URL만 사용
result["상품 링크"] = (
    result["images"]
    .fillna("")
    .str.split(" ~ ")
    .str[0]
    .apply(
        lambda url: (
            f'<a href="{url}" target="_blank">상품 보기</a>'
            if url else ""
        )
    )
)

result_korean = result.rename(columns={
    "name": "상품명",
    "brand": "브랜드",
    "gender": "성별",
    "price": "가격",
    "similarity": "유사도"
})

display(HTML(
    result_korean[
        ["상품명", "브랜드", "성별", "가격", "유사도", "상품 링크"]
    ].to_html(
        escape=False,
        index=False
    )
))

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\study-with-ai\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Lee\.cache\huggingface\hub\models--dragonkue--BGE-m3-ko. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/201 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/31.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/698 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.27GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.36k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

In [95]:
load_dotenv()

True

1536